QBShared = QBShared or {}
QBShared.Weapons = {
	-- // WEAPONS
	-- Melee
	[`weapon_unarmed`] 				 = {['name'] = 'weapon_unarmed', 		['label'] = 'Fists', 				['ammotype'] = nil, ['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_dagger`] 				 = {['name'] = 'weapon_dagger', 		['label'] = 'Dagger', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_bat`] 					 = {['name'] = 'weapon_bat', 			['label'] = 'Bat', 					['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_bottle`] 				 = {['name'] = 'weapon_bottle', 		['label'] = 'Broken Bottle', 		['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_crowbar`] 				 = {['name'] = 'weapon_crowbar', 		['label'] = 'Crowbar', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_flashlight`] 			 = {['name'] = 'weapon_flashlight', 	['label'] = 'Flashlight', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_golfclub`] 			 = {['name'] = 'weapon_golfclub', 		['label'] = 'Golfclub', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_hammer`] 				 = {['name'] = 'weapon_hammer', 		['label'] = 'Hammer', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_hatchet`] 				 = {['name'] = 'weapon_hatchet', 		['label'] = 'Hatchet', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_knuckle`] 				 = {['name'] = 'weapon_knuckle', 		['label'] = 'Knuckle', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_knife`] 				 = {['name'] = 'weapon_knife', 			['label'] = 'Knife', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_machete`] 				 = {['name'] = 'weapon_machete', 		['label'] = 'Machete', 				['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_switchblade`] 			 = {['name'] = 'weapon_switchblade', 	['label'] = 'Switchblade', 			['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_nightstick`] 			 = {['name'] = 'weapon_nightstick', 	['label'] = 'Nightstick', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_wrench`] 				 = {['name'] = 'weapon_wrench', 		['label'] = 'Wrench', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_battleaxe`] 			 = {['name'] = 'weapon_battleaxe', 		['label'] = 'Battle Axe', 			['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_poolcue`] 				 = {['name'] = 'weapon_poolcue', 		['label'] = 'Poolcue', 				['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_briefcase`] 			 = {['name'] = 'weapon_briefcase', 		['label'] = 'Briefcase', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_briefcase_02`] 		 = {['name'] = 'weapon_briefcase_02', 	['label'] = 'Briefcase', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_garbagebag`] 			 = {['name'] = 'weapon_garbagebag', 	['label'] = 'Garbage Bag', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_handcuffs`] 			 = {['name'] = 'weapon_handcuffs', 		['label'] = 'Handcuffs', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_bread`] 				 = {['name'] = 'weapon_bread', 			['label'] = 'Baquette', 			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_stone_hatchet`] 		 = {['name'] = 'weapon_stone_hatchet', 	['label'] = 'Weapon Stone Hatchet', ['ammotype'] = nil,	['damagereason'] = 'Knifed / Stabbed / Eviscerated'},

    -- Handguns
	[`weapon_pistol`] 				 = {['name'] = 'weapon_pistol', 		['label'] = 'Walther P99', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_pistol_mk2`] 			 = {['name'] = 'weapon_pistol_mk2', 	['label'] = 'Pistol Mk II', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_combatpistol`] 		 = {['name'] = 'weapon_combatpistol', 	['label'] = 'Combat Pistol', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_appistol`] 			 = {['name'] = 'weapon_appistol', 		['label'] = 'AP Pistol', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_stungun`] 				 = {['name'] = 'weapon_stungun', 		['label'] = 'Taser', 					['ammotype'] = 'AMMO_STUNGUN',	['damagereason'] = 'Died'},
	[`weapon_pistol50`] 			 = {['name'] = 'weapon_pistol50', 		['label'] = 'Pistol .50 Cal', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_snspistol`] 			 = {['name'] = 'weapon_snspistol', 		['label'] = 'SNS Pistol', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_snspistol_mk2`] 	     = {['name'] = 'weapon_snspistol_mk2', 	['label'] = 'SNS Pistol MK2', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_heavypistol`] 			 = {['name'] = 'weapon_heavypistol', 	['label'] = 'Heavy Pistol', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_vintagepistol`] 		 = {['name'] = 'weapon_vintagepistol', 	['label'] = 'Vintage Pistol', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_flaregun`] 			 = {['name'] = 'weapon_flaregun', 		['label'] = 'Flare Gun', 				['ammotype'] = 'AMMO_FLARE',	['damagereason'] = 'Died'},
	[`weapon_marksmanpistol`] 		 = {['name'] = 'weapon_marksmanpistol', ['label'] = 'Marksman Pistol', 			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_revolver`] 			 = {['name'] = 'weapon_revolver', 		['label'] = 'Revolver', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_revolver_mk2`] 		 = {['name'] = 'weapon_revolver_mk2', 	['label'] = 'Violence', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_doubleaction`] 	     = {['name'] = 'weapon_doubleaction', 	['label'] = 'Double Action Revolver',	['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_raypistol`]			 = {['name'] = 'weapon_raypistol',		['label'] = 'Weapon Raypistol',			['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_ceramicpistol`]		 = {['name'] = 'weapon_ceramicpistol', 	['label'] = 'Weapon Ceramicpistol',		['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_navyrevolver`]        	 = {['name'] = 'weapon_navyrevolver', 	['label'] = 'Weapon Navyrevolver',		['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_gadgetpistol`] 		 = {['name'] = 'weapon_gadgetpistol', 	['label'] = 'Weapon Gadgetpistol',		['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_stungun_mp`] 			 = {['name'] = 'weapon_stungun_mp', 	['label'] = 'Taser', 					['ammotype'] = 'AMMO_STUNGUN',	['damagereason'] = 'Died'},

    -- Submachine Guns
	[`weapon_microsmg`] 			 = {['name'] = 'weapon_microsmg', 		['label'] = 'Micro SMG', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_smg`] 				 	 = {['name'] = 'weapon_smg', 			['label'] = 'SMG', 					['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_smg_mk2`] 				 = {['name'] = 'weapon_smg_mk2', 		['label'] = 'PD MP5 2', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_assaultsmg`] 			 = {['name'] = 'weapon_assaultsmg', 	['label'] = 'Assault SMG', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_combatpdw`] 			 = {['name'] = 'weapon_combatpdw', 		['label'] = 'Combat PDW', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_machinepistol`] 		 = {['name'] = 'weapon_machinepistol', 	['label'] = 'Tec-9', 				['ammotype'] = 'AMMO_PISTOL',	['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_minismg`] 				 = {['name'] = 'weapon_minismg', 		['label'] = 'Mini SMG', 			['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_raycarbine`]	         = {['name'] = 'weapon_raycarbine', 	['label'] = 'Weapon Raycarbine',	['ammotype'] = 'AMMO_SMG',		['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},

    -- Shotguns
	[`weapon_pumpshotgun`] 			 = {['name'] = 'weapon_pumpshotgun', 	 	['label'] = 'Pump Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_pumpshotgun_mk2`]		 = {['name'] = 'weapon_pumpshotgun_mk2',	['label'] = 'Pumpshotgun MK2', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_sawnoffshotgun`] 		 = {['name'] = 'weapon_sawnoffshotgun', 	['label'] = 'Sawn-off Shotgun', 		['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_assaultshotgun`] 		 = {['name'] = 'weapon_assaultshotgun', 	['label'] = 'Assault Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_bullpupshotgun`] 		 = {['name'] = 'weapon_bullpupshotgun', 	['label'] = 'Bullpup Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_musket`] 			     = {['name'] = 'weapon_musket', 			['label'] = 'Musket', 					['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_heavyshotgun`] 		 = {['name'] = 'weapon_heavyshotgun', 	 	['label'] = 'Heavy Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_dbshotgun`] 			 = {['name'] = 'weapon_dbshotgun', 		 	['label'] = 'Double-barrel Shotgun', 	['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_autoshotgun`] 			 = {['name'] = 'weapon_autoshotgun', 	 	['label'] = 'Auto Shotgun', 			['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_combatshotgun`]		 = {['name'] = 'weapon_combatshotgun', 		['label'] = 'Weapon Combatshotgun',		['ammotype'] = 'AMMO_SHOTGUN',	['damagereason'] = 'Devastated / Pulverized / Shotgunned'},

    -- Assault Rifles
	[`weapon_assaultrifle`] 		 = {['name'] = 'weapon_assaultrifle', 	 	['label'] = 'Assault Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_assaultrifle_mk2`] 	 = {['name'] = 'weapon_assaultrifle_mk2', 	['label'] = 'AK-47 MK2', 					['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_carbinerifle`] 		 = {['name'] = 'weapon_carbinerifle', 	 	['label'] = 'Carbine Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_carbinerifle_mk2`] 	 = {['name'] = 'weapon_carbinerifle_mk2', 	['label'] = 'PD 762', 						['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_advancedrifle`] 		 = {['name'] = 'weapon_advancedrifle', 	 	['label'] = 'Advanced Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_specialcarbine`] 		 = {['name'] = 'weapon_specialcarbine', 	['label'] = 'Special Carbine', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_specialcarbine_mk2`]	 = {['name'] = 'weapon_specialcarbine_mk2',	['label'] = 'Weapon Wpecialcarbine MK2',	['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_bullpuprifle`] 		 = {['name'] = 'weapon_bullpuprifle', 	 	['label'] = 'Bullpup Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_bullpuprifle_mk2`]		 = {['name'] = 'weapon_bullpuprifle_mk2', 	['label'] = 'Bull Puprifle MK2',			['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_compactrifle`] 		 = {['name'] = 'weapon_compactrifle', 	 	['label'] = 'Compact Rifle', 				['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_militaryrifle`]		 = {['name'] = 'weapon_militaryrifle', 		['label'] = 'Weapon Militaryrifle',			['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
    [`weapon_heavyrifle`] 			 = {['name'] = 'weapon_heavyrifle', 	 	['label'] = 'Heavy Rifle', 					['ammotype'] = 'AMMO_RIFLE',	['damagereason'] = 'Ended / Rifled / Shot down / Floored'},

    -- Light Machine Guns
	[`weapon_mg`] 					 = {['name'] = 'weapon_mg', 			['label'] = 'Machinegun', 			['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_combatmg`] 			 = {['name'] = 'weapon_combatmg', 		['label'] = 'Combat MG', 			['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_combatmg_mk2`]	 		 = {['name'] = 'weapon_combatmg_mk2', 	['label'] = 'Weapon Combatmg MK2',	['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},
	[`weapon_gusenberg`] 			 = {['name'] = 'weapon_gusenberg', 		['label'] = 'Thompson SMG', 		['ammotype'] = 'AMMO_MG',	['damagereason'] = 'Machine gunned / Sprayed / Ruined'},

    -- Sniper Rifles
	[`weapon_sniperrifle`] 			 = {['name'] = 'weapon_sniperrifle', 	 	['label'] = 'Sniper Rifle', 			['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_heavysniper`] 			 = {['name'] = 'weapon_heavysniper', 	 	['label'] = 'Heavy Sniper', 			['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_heavysniper_mk2`]		 = {['name'] = 'weapon_heavysniper_mk2', 	['label'] = 'Weapon Heavysniper MK2',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_marksmanrifle`] 		 = {['name'] = 'weapon_marksmanrifle', 	 	['label'] = 'Marksman Rifle', 			['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_marksmanrifle_mk2`]	 = {['name'] = 'weapon_marksmanrifle_mk2',	['label'] = 'Weapon Marksmanrifle MK2',	['ammotype'] = 'AMMO_SNIPER',			['damagereason'] = 'Sniped / Picked off / Scoped'},
	[`weapon_remotesniper`] 		 = {['name'] = 'weapon_remotesniper', 	 	['label'] = 'Remote Sniper', 			['ammotype'] = 'AMMO_SNIPER_REMOTE',	['damagereason'] = 'Sniped / Picked off / Scoped'},

    -- Heavy Weapons
	[`weapon_rpg`] 					 = {['name'] = 'weapon_rpg', 			      	['label'] = 'RPG', 						['ammotype'] = 'AMMO_RPG',				['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_grenadelauncher`] 		 = {['name'] = 'weapon_grenadelauncher', 	  	['label'] = 'Grenade Launcher', 		['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_grenadelauncher_smoke`] = {['name'] = 'weapon_grenadelauncher_smoke',	['label'] = 'Smoke Grenade Launcher',	['ammotype'] = 'AMMO_GRENADELAUNCHER',	['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_minigun`] 				 = {['name'] = 'weapon_minigun', 		      	['label'] = 'Minigun', 					['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_firework`] 			 = {['name'] = 'weapon_firework', 		 	  	['label'] = 'Firework Launcher', 		['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_railgun`] 				 = {['name'] = 'weapon_railgun', 		 	  	['label'] = 'Railgun', 					['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_hominglauncher`] 		 = {['name'] = 'weapon_hominglauncher', 	 	['label'] = 'Homing Launcher', 			['ammotype'] = 'AMMO_STINGER',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_compactlauncher`] 		 = {['name'] = 'weapon_compactlauncher',  	  	['label'] = 'Compact Launcher', 		['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_rayminigun`]			 = {['name'] = 'weapon_rayminigun', 		 	['label'] = 'Weapon Rayminigun',		['ammotype'] = 'AMMO_MINIGUN',			['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
    [`weapon_emplauncher`] 			 = {['name'] = 'weapon_emplauncher', 			['label'] = 'EMP Launcher', 			['ammotype'] = 'AMMO_EMPLAUNCHER',		['damagereason'] = 'Died'},

    -- Throwables
	[`weapon_grenade`] 		 = {['name'] = 'weapon_grenade', 		['label'] = 'Grenade', 			['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_bzgas`] 		 = {['name'] = 'weapon_bzgas', 			['label'] = 'BZ Gas', 			['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_molotov`] 		 = {['name'] = 'weapon_molotov', 		['label'] = 'Molotov', 			['ammotype'] = nil,				['damagereason'] = 'Torched / Flambeed / Barbecued'},
	[`weapon_stickybomb`] 	 = {['name'] = 'weapon_stickybomb', 	['label'] = 'C4', 				['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_proxmine`] 	 = {['name'] = 'weapon_proxmine', 		['label'] = 'Proxmine Grenade', ['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_snowball`] 	 = {['name'] = 'weapon_snowball', 		['label'] = 'Snowball', 		['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_pipebomb`] 	 = {['name'] = 'weapon_pipebomb', 		['label'] = 'Pipe Bomb', 		['ammotype'] = nil,				['damagereason'] = 'Bombed / Exploded / Detonated / Blew up'},
	[`weapon_ball`] 		 = {['name'] = 'weapon_ball', 			['label'] = 'Ball', 			['ammotype'] = 'AMMO_BALL',		['damagereason'] = 'Died'},
	[`weapon_smokegrenade`]  = {['name'] = 'weapon_smokegrenade', 	['label'] = 'Smoke Grenade', 	['ammotype'] = nil,				['damagereason'] = 'Died'},
	[`weapon_flare`] 		 = {['name'] = 'weapon_flare', 			['label'] = 'Flare pistol', 	['ammotype'] = 'AMMO_FLARE',	['damagereason'] = 'Died'},

    -- Miscellaneous
	[`weapon_petrolcan`] 			= {['name'] = 'weapon_petrolcan', 		 	['label'] = 'Petrol Can', 				['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Died'},
	[`gadget_parachute`] 			= {['name'] = 'gadget_parachute', 		 	['label'] = 'Parachute', 				['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_fireextinguisher`] 	= {['name'] = 'weapon_fireextinguisher',	['label'] = 'Fire Extinguisher',		['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_hazardcan`]			= {['name'] = 'weapon_hazardcan',			['label'] = 'Weapon Hazardcan',			['ammotype'] = 'AMMO_PETROLCAN',		['damagereason'] = 'Died'},
    [`weapon_fertilizercan`]		= {['name'] = 'weapon_fertilizercan',		['label'] = 'Fertilizer Can',			['ammotype'] = 'AMMO_FERTILIZERCAN',	['damagereason'] = 'Died'},
	[`weapon_barbed_wire`]			= {['name'] = 'weapon_barbed_wire',			['label'] = 'Barbed Wire',				['ammotype'] = nil,						['damagereason'] = 'Prodded'},
	[`weapon_drowning`]				= {['name'] = 'weapon_drowning',			['label'] = 'Drowning',					['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_drowning_in_vehicle`]	= {['name'] = 'weapon_drowning_in_vehicle',	['label'] = 'Drowning in a Vehicle',	['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_bleeding`]				= {['name'] = 'weapon_bleeding',			['label'] = 'Bleeding',					['ammotype'] = nil,						['damagereason'] = 'Bled out'},
	[`weapon_electric_fence`]		= {['name'] = 'weapon_electric_fence',		['label'] = 'Electric Fence',			['ammotype'] = nil,						['damagereason'] = 'Fried'},
	[`weapon_explosion`]			= {['name'] = 'weapon_explosion',			['label'] = 'Explosion',				['ammotype'] = nil,						['damagereason'] = 'Killed / Exploded / Obliterated / Destroyed / Erased / Annihilated'},
	[`weapon_fall`]					= {['name'] = 'weapon_fall',				['label'] = 'Fall',						['ammotype'] = nil,						['damagereason'] = 'Committed suicide'},
	[`weapon_exhaustion`]			= {['name'] = 'weapon_exhaustion',			['label'] = 'Exhaustion',				['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_hit_by_water_cannon`]	= {['name'] = 'weapon_hit_by_water_cannon',	['label'] = 'Water Cannon',				['ammotype'] = nil,						['damagereason'] = 'Died'},
	[`weapon_rammed_by_car`]		= {['name'] = 'weapon_rammed_by_car',		['label'] = 'Rammed - Vehicle',			['ammotype'] = nil,						['damagereason'] = 'Flattened / Ran over / Ran down'},
	[`weapon_run_over_by_car`]		= {['name'] = 'weapon_run_over_by_car',		['label'] = 'Run Over - Vehicle',		['ammotype'] = nil,						['damagereason'] = 'Flattened / Ran over / Ran down'},
	[`weapon_heli_crash`]			= {['name'] = 'weapon_heli_crash',			['label'] = 'Heli Crash',				['ammotype'] = nil,						['damagereason'] = 'Helicopter Crash'},
	[`weapon_fire`]					= {['name'] = 'weapon_fire',				['label'] = 'Fire',						['ammotype'] = nil,						['damagereason'] = 'Torched / Flambeed / Barbecued'},

	--V2 Weapons
	[`weapon_ak47`] 		 		= {['name'] = 'weapon_ak47', 				['label'] = 'AK-47', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m70`] 		 	 		= {['name'] = 'weapon_m70', 				['label'] = 'M70', 						['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_de`] 			 		= {['name'] = 'weapon_de', 					['label'] = 'Desert Eagle', 			['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_fnx45`] 			 	= {['name'] = 'weapon_fnx45', 				['label'] = 'FN FNX45', 				['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_glock17`] 			 	= {['name'] = 'weapon_glock17', 			['label'] = 'PD Glock 17', 				['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_m4`] 		 			= {['name'] = 'weapon_m4', 	 				['label'] = 'PD M4A1', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m9`] 			 		= {['name'] = 'weapon_m9', 					['label'] = 'Beretta M9A3', 			['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_m1911`] 			 	= {['name'] = 'weapon_m1911', 				['label'] = 'M1911', 					['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_uzi`] 			 		= {['name'] = 'weapon_uzi', 				['label'] = 'UZI', 						['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_mac10`] 				= {['name'] = 'weapon_mac10', 				['label'] = 'MAC-10', 					['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_mossberg`] 		 	= {['name'] = 'weapon_mossberg', 			['label'] = 'Mossberg 500', 			['ammotype'] = 'AMMO_SHOTGUN',		['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_remington`] 		 	= {['name'] = 'weapon_remington', 			['label'] = 'Remington 870', 			['ammotype'] = 'AMMO_SHOTGUN',		['damagereason'] = 'Devastated / Pulverized / Shotgunned'},
	[`weapon_scarh`] 		 		= {['name'] = 'weapon_scarh', 				['label'] = 'PD SCAR-H', 				['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_shiv`] 				= {['name'] = 'weapon_shiv', 				['label'] = 'Shiv', 					['ammotype'] = nil,					['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_katana`] 				= {['name'] = 'weapon_katana', 				['label'] = 'Katana', 					['ammotype'] = nil,					['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_sledgehammer`] 		= {['name'] = 'weapon_sledgehammer', 		['label'] = 'Sledge Hammer', 			['ammotype'] = nil,					['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
    [`weapon_ar15`] 				= {['name'] = 'weapon_ar15', 	 			['label'] = 'PD AR-15', 				['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mk14`] 				= {['name'] = 'weapon_mk14', 	 			['label'] = 'PD MK14', 					['ammotype'] = 'AMMO_SNIPER',		['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
	[`weapon_huntingrifle`] 		= {['name'] = 'weapon_huntingrifle', 	 	['label'] = 'Hunting Rifle', 			['ammotype'] = 'AMMO_SNIPER',		['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
	[`weapon_mp9`] 					= {['name'] = 'weapon_mp9', 				['label'] = 'MP9', 						['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Riddled / Drilled / Finished / Submachine Gunned'},
	[`weapon_m110`] 				= {['name'] = 'weapon_m110', 	 			['label'] = 'M110', 					['ammotype'] = 'AMMO_SNIPER',		['damagereason'] = 'Ended / Sniped / Shot down / Floored'},
	[`weapon_hk416`] 		 		= {['name'] = 'weapon_hk416', 	 			['label'] = 'HK-416', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_a91`] 		 			= {['name'] = 'weapon_a91', 	 			['label'] = 'A91', 						['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_acr`] 		 			= {['name'] = 'weapon_acr', 	 			['label'] = 'ACR', 						['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_aek971`] 	 			= {['name'] = 'weapon_aek971', 				['label'] = 'AEK971', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ak5c`] 	 			= {['name'] = 'weapon_ak5c', 	 			['label'] = 'AK5C', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_aks`] 		 			= {['name'] = 'weapon_aks', 	 			['label'] = 'AKS', 						['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_an94`] 	 			= {['name'] = 'weapon_an94', 	 			['label'] = 'AN94', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_aug`] 		 			= {['name'] = 'weapon_aug', 	 			['label'] = 'AUG', 						['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_aug_a3`] 	 			= {['name'] = 'weapon_aug_a3', 				['label'] = 'AUG_A3', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_cbj_ms`] 	 			= {['name'] = 'weapon_cbj_ms', 				['label'] = 'CBJ-MS', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_cz61`] 	 			= {['name'] = 'weapon_cz61', 			 	['label'] = 'CZ61', 					['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_fn57`] 	 			= {['name'] = 'weapon_fn57', 	 			['label'] = 'Fn57', 					['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_g3a3`] 	 			= {['name'] = 'weapon_g3a3', 			 	['label'] = 'g3A3',						['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_galil`] 	 			= {['name'] = 'weapon_galil', 	 			['label'] = 'GALIL', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_groza4`] 	 			= {['name'] = 'weapon_groza4', 				['label'] = 'GROZA4', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_hipower`] 	 			= {['name'] = 'weapon_hipower', 			['label'] = 'HIPOWER', 					['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_lawrc45`] 	 			= {['name'] = 'weapon_lawrc45', 			['label'] = 'LAWRC45', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m4a1`] 	 			= {['name'] = 'weapon_m4a1', 			 	['label'] = 'M4A1', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m4a1_02`] 	 			= {['name'] = 'weapon_m4a1_02', 			['label'] = 'M4A1_02', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m16a4`] 	 			= {['name'] = 'weapon_m16a4', 	 			['label'] = 'M16A4', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m39`] 		 			= {['name'] = 'weapon_m39', 	 			['label'] = 'M39', 						['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_m416`] 	 			= {['name'] = 'weapon_m416', 	 			['label'] = 'M416', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mk18`] 	 			= {['name'] = 'weapon_mk18', 	 			['label'] = 'Mk18', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mp5`] 		 			= {['name'] = 'weapon_mp5', 	 			['label'] = 'MP5', 						['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mp7`] 		 			= {['name'] = 'weapon_mp7', 			 	['label'] = 'MP7', 						['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mpx`] 		 			= {['name'] = 'weapon_mpx', 			 	['label'] = 'MPX', 						['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mtar21`] 	 			= {['name'] = 'weapon_mtar21', 				['label'] = 'MTAR21', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ppsh`] 	 			= {['name'] = 'weapon_ppsh', 	 			['label'] = 'PPSH', 					['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_qsz92`] 	 			= {['name'] = 'weapon_qsz92', 	 			['label'] = 'QSZ92', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_sa58`] 	 			= {['name'] = 'weapon_sa58', 	 			['label'] = 'SA58', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_scorpion`] 			= {['name'] = 'weapon_scorpion', 			['label'] = 'SCORPION',					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_sg553`] 	 			= {['name'] = 'weapon_sg553', 	 			['label'] = 'SG553', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_warlord_ak`]  			= {['name'] = 'weapon_warlord_ak',			['label'] = 'WARLORD', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ak47_02`]  			= {['name'] = 'weapon_ak47_02', 			['label'] = 'AK47 II', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ak47_03`]  			= {['name'] = 'weapon_ak47_03', 			['label'] = 'AK47 III', 				['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_vector`] 				= {['name'] = 'weapon_vector', 				['label'] = 'Vector', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_honeybadger`] 	 		= {['name'] = 'weapon_honeybadger', 		['label'] = 'Honeybadger', 				['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_votovepr`] 	 		= {['name'] = 'weapon_votovepr', 			['label'] = 'Molot Vepr-12', 			['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_dp12`] 	 			= {['name'] = 'weapon_dp12', 				['label'] = 'DP-12', 					['ammotype'] = 'AMMO_SHOTGUN',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_ump`] 	 				= {['name'] = 'weapon_ump', 				['label'] = 'UMP', 						['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_fal`] 	 				= {['name'] = 'weapon_fal', 				['label'] = 'FN FAL', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_mcx`] 	 				= {['name'] = 'weapon_mcx', 				['label'] = 'MCX', 						['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Ended / Rifled / Shot down / Floored'},
	[`weapon_dildo`] 	 			= {['name'] = 'weapon_dildo', 				['label'] = 'Dildo Bat', 				['weapontype'] = 'Melee',			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_baton`] 	 			= {['name'] = 'weapon_baton', 				['label'] = 'PD Baton', 				['weapontype'] = 'Melee',			['ammotype'] = nil,	['damagereason'] = 'Melee killed / Whacked / Executed / Beat down / Murdered / Battered'},
	[`weapon_colt_m45a1`] 			= {['name'] = 'weapon_colt_m45a1', 			['label'] = 'Colt M45A1', 				['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_vp9`] 			 		= {['name'] = 'weapon_vp9', 				['label'] = 'HK VP9', 					['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_kimber`] 			 	= {['name'] = 'weapon_kimber', 				['label'] = 'Kimber Eclipse', 			['ammotype'] = 'AMMO_PISTOL',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_p416`] 			 	= {['name'] = 'weapon_p416', 				['label'] = 'POF P416', 				['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_akcompact`] 			= {['name'] = 'weapon_akcompact', 			['label'] = 'AK COMPACT', 				['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_pp19bizon`] 			= {['name'] = 'weapon_pp19bizon', 			['label'] = 'PP19 Bizon', 				['ammotype'] = 'AMMO_SMG',			['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_famas`] 				= {['name'] = 'weapon_famas', 				['label'] = 'FAMAS', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_beanbag`] 				= {['name'] = 'weapon_beanbag', 			['label'] = 'PD Beanbag', 				['ammotype'] = 'AMMO_SHOTGUN',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_msbs`] 				= {['name'] = 'weapon_msbs', 				['label'] = 'MSBS', 					['ammotype'] = 'AMMO_RIFLE',		['damagereason'] = 'Pistoled / Blasted / Plugged / Bust a cap in'},
	[`weapon_tkatana`] 				= {['name'] = 'weapon_tkatana', 			['label'] = 'Thermal Katana', 			['ammotype'] = nil,					['damagereason'] = 'Knifed / Stabbed / Eviscerated'},
	[`weapon_blade`] 				= {['name'] = 'weapon_blade', 				['label'] = 'BLADE', 					['ammotype'] = nil,					['damagereason'] = 'Knifed / Stabbed / Eviscerated'},

	-- Animals
	[`weapon_animal`]	= {['name'] = 'weapon_animal',	['label'] = 'Animal',	['ammotype'] = nil,	['damagereason'] = 'Mauled'},
    [`weapon_cougar`]	= {['name'] = 'weapon_cougar',	['label'] = 'Cougar',	['ammotype'] = nil,	['damagereason'] = 'Mauled'},
}