print("^2Jim^7-^2Shops v^41^7.^47 ^7- ^2Shop Script by ^1Jimathy^7")

-- If you need support I now have a discord available, it helps me keep track of issues and give better support.

-- https://discord.gg/xKgQZ6wZvS

Config = {
	Debug = false, -- Enable to add debug boxes and message.
	img = "qb-inventory/html/images/", -- Set this to your inventory
	JimMenu = true, -- Enable this if you are using an updated qb-menu resource with icon support
	Peds = true, -- Set to true if you want Shops to have Peds
	Limit = false, -- Enable this to add Stash features, This adds limits to items and gets refilled at each restart
	MaxSlots = 41, -- Set this to your player inventory slot count, this is default "41"
	BlackMarket = true, -- enable to add blackmarket locations (defined at the bottom of this file)
	Measurement = "lb", -- Custom Weight measurement
	Gabz247 = true,  -- Enable if using gabz 247 stores
	GabzAmmu = true, -- Enable if using gabz Ammunation stores
	VendOverride = false, -- Enable this if you want all the vending machines to use this script
	RandomAmount = false, -- Sets wether a stash should have a "random" amount of stock or full.

	Scenarios = { -- List of scenarios the peds do, This is called "fun", much better than standing staring at the void.
		"WORLD_HUMAN_GUARD_PATROL",
		"WORLD_HUMAN_JANITOR",
		"WORLD_HUMAN_MUSCLE_FLEX",
		"PROP_HUMAN_STAND_IMPATIENT",
		"WORLD_HUMAN_VALET",
		"WORLD_HUMAN_AA_COFFEE",
		"WORLD_HUMAN_AA_SMOKE",
		"WORLD_HUMAN_DRUG_DEALER",
		"WORLD_HUMAN_GUARD_STAND_CASINO",
	},
	Products = {
		["normal"] = {
			{ name = "pepsi_cola", price = 4, amount = 50, info = {} },
			{ name = "water_bottle", price = 4, amount = 50, info = {} },				
			{ name = "mountain_dew", price = 4, amount = 50, info = {} },
			{ name = "dr_pepper", price = 4, amount = 50, info = {} },
			{ name = "sprite", price = 4, amount = 50, info = {} },
			{ name = "a_and_w_root_beer", price = 4, amount = 50, info = {} },
			{ name = "brisk_half_and_half", price = 4, amount = 50, info = {} },
			{ name = "brisk_sweet_tea", price = 4, amount = 50, info = {} },
			{ name = "brisk_blackberry_smash", price = 4, amount = 50, info = {} },
			{ name = "pure_leaf", price = 4, amount = 50, info = {} },
			{ name = "slurpee", price = 6, amount = 50, info = {} },
			{ name = "gatorade_fierce_grape", price = 4, amount = 50, info = {} },
			{ name = "gatorade_frost_arctic_blitz", price = 4, amount = 50, info = {} },
			{ name = "gatorade_strawberry_lemonade", price = 4, amount = 50, info = {} },
            { name = "gatorade_fierce_blue_cherry", price = 4, amount = 50, info = {} },
			{ name = "gatorade_frost_glacier_cherry", price = 4, amount = 50, info = {} },
			{ name = "gatorade_lime_cucumber", price = 4, amount = 50, info = {} },
			{ name = "gatorade_orange", price = 4, amount = 50, info = {} },
			{ name = "gatorade_fruit_punch", price = 4, amount = 50, info = {} },
			{ name = "gatorade_lemon_lime", price = 4, amount = 50, info = {} },
			{ name = "monster", price = 6, amount = 6, info = {} },
			{ name = "rockstar", price = 6, amount = 6, info = {} },
			{ name = "bang_energy", price = 4, amount =6, info = {} },
			{ name = "red_bull_red_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_pear_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_peach_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_coconut_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_blue_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_green_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_orange_edition", price = 6, amount = 50, info = {} },
			{ name = "funyuns_onion", price = 6, amount = 50, info = {} },
			{ name = "cheetos_cheese", price = 4, amount = 50, info = {} },
			{ name = "cheetos_hot", price = 4, amount = 50, info = {} },
			{ name = "ruffles_potato_chip", price = 4, amount = 50, info = {} },
			{ name = "doritos_nacho", price = 4, amount = 50, info = {} },
			{ name = "pringles", price = 4, amount = 50, info = {} },
			{ name = "rice_krispies_treats", price = 4, amount = 50, info = {} },
			{ name = "lays_potato", price = 4, amount = 50, info = {} },
			{ name = "cheezit_Baked", price = 4, amount = 50, info = {} },
			{ name = "oreo", price = 4, amount = 50, info = {} },
			{ name = "cheetos_cheese", price = 4, amount = 50, info = {} },
			{ name = "ding_dongs", price = 4, amount = 50, info = {} },
			{ name = "ruffles_potato_chip", price = 4, amount = 50, info = {} },
			{ name = "sunflower_seeds", price = 4, amount = 50, info = {} },
			{ name = "twix", price = 10, amount = 4, info = {} },
			{ name = "mr_goodbar", price = 4, amount = 50, info = {} },
			{ name = "hershey_bar", price = 4, amount = 50, info = {} },
			{ name = "whoopers", price = 4, amount = 50, info = {} },
			{ name = "crunch", price = 4, amount = 50, info = {} },
			{ name = "kit_kat", price = 4, amount = 50, info = {} },
			{ name = "nerds", price = 4, amount = 50, info = {} },
			{ name = "steak_cheese_taquito", price = 10, amount = 50, info = {} },
			{ name = "beef_mini_tacos", price = 12, amount = 50, info = {} },
			{ name = "crunch", price = 4, amount = 50, info = {} },
        	{ name = "potato_wedges", price = 4, amount = 50, info = {} },
			{ name = "buffalo_chicken_roller", price =12, amount = 50, info = {} },
			{ name = "jalapeno_cheese_taquito", price = 12, amount = 50, info = {} },
			{ name = "fruit_medley", price = 12, amount = 50, info = {} },
		},
		["gunpowder"] = {
			{ name = "sulfur", price = 450, amount = 10000, info = {} },
			{ name = "carbon", price = 450, amount = 10000, info = {} },
			{ name = "potassium_nitrate", price = 900, amount = 1000, info = {} },
		},
		["hardware"] = {
			{ name = "lockpick", price = 200, amount = 1000, info = {} },
			{ name = "repairkit", price = 25, amount = 50, info = {}, requiredJob = { "mechanic", "police", "tuner" } },
			{ name = "screwdriverset", price = 750, amount = 50, info = {} },
			{ name = "phone", price = 500, amount = 1, info = {} },
			{ name = "radio", price = 500, amount = 1, info = {} },
			{ name = "binoculars", price = 150, amount = 50, info = {} },
			{ name = "firework1", price = 550, amount = 50, info = {} },
			{ name = "firework2", price = 550, amount = 50, info = {} },
			{ name = "firework3", price = 550, amount = 50, info = {} },
			{ name = "firework4", price = 550, amount = 50, info = {} },
			{ name = "fitbit", price = 1500, amount = 1, info = {} },
			{ name = "cleaningkit", price = 250, amount = 150, info = {} },
			{ name = "advancedrepairkit", price = 50, amount = 50, info = {}, requiredJob = { "mechanic", "police" } },
			{ name = "stickynotepad", price = 5, amount = 50, info = {} },
			{ name = "cups", price = 500, amount = 50, info = {} },
			{ name = "yogamat", price = 100, amount = 10, info = {} },
			{ name = "boombox", price = 2500, amount = 10, info = {} },
			{ name = "skateboard", price = 2500, amount = 1, info = {} },
		},
		["jewelry"] = {
			{ name = "gallery_aquamarinering", price = 500, amount = 1000, info = {} },
			{ name = "gallery_citrinering", price = 500, amount = 1000, info = {} },
			{ name = "gallery_diamondring", price = 500, amount = 1000, info = {} },
			{ name = "gallery_jadering", price = 500, amount = 1000, info = {} },
			{ name = "gallery_onyxring", price = 500, amount = 1000, info = {} },
			{ name = "gallery_rubyring", price = 500, amount = 1000, info = {} },
			{ name = "gallery_sapphirering", price = 500, amount = 1000, info = {} },
			{ name = "gallery_tanzanitering", price = 500, amount = 1000, info = {} },
		},
		["gearshop"] = {
			{ name = "diving_gear", price = 1500, amount = 1, info = {} },
			{ name = "jerry_can", price = 250, amount = 1, info = {} },
			{ name = "yogamat", price = 100, amount = 10, info = {} },
		},
		["leisureshop"] = {
			{ name = "parachute", price = 1000, amount = 1, info = {} },
			{ name = "binoculars", price = 150, amount = 50, info = {} },    
			{ name = "diving_gear", price = 1500, amount = 1, info = {} },
			{ name = "harness", price = 1000, amount = 1, info = {} },
			{ name = "jerry_can", price = 250, amount = 1, info = {} },
			{ name = "cups", price = 500, amount = 1, info = {} },
			{ name = "yogamat", price = 100, amount = 10, info = {} },
			{ name = "skateboard", price = 2500, amount = 1, info = {} },
		},
		["weapons"] = {
			{ name = "weapon_knife", price = 1000, amount = 10, info = nil },
			{ name = "weapon_bat", price = 2500, amount = 10, info = {} },
			{ name = "weapon_knuckle", price = 5000, amount = 10, info = {} },
			{ name = "weapon_pistol", price = 5500, amount = 1, info = nil, requiresLicense = true },
			{ name = "weapon_heavypistol", price = 8500, amount = 1, info = nil, requiresLicense = true },
			{ name = "weapon_ceramicpistol", price = 9500, amount = 1, info = nil, requiresLicense = true },
			{ name = "weapon_vintagepistol", price = 10000, amount = 1, info = nil, requiresLicense = true },
			{ name = "weapon_huntingrifle", price = 8500, amount = 1, info = nil, requiresLicense = true },
			{ name = "pistol_ammo", price = 350, amount = 2500, info = {}, requiresLicense = true },
			{ name = "smg_ammo", price = 450, amount = 2500, info = {}, requiresLicense = true },
			{ name = "rifle_ammo", price = 550, amount = 2500, info = {}, requiresLicense = true },
			{ name = "snp_ammo", price = 550, amount = 2500, info = {}, requiresLicense = true },
			{ name = "weapontint_black", price = 150, amount = 25, info = {}, requiresLicense = true },
			{ name = "weapontint_green", price = 150, amount = 25, info = {}, requiresLicense = true },
			{ name = "weapontint_gold", price = 150, amount = 25, info = {}, requiresLicense = true },
			{ name = "weapontint_orange", price = 150, amount = 25, info = {}, requiresLicense = true },
		},
		["pdshop"] = {
			{ name = "speedball", price = 2, amount = 50, info = {} },
			{ name = "pepsi_cola", price = 2, amount = 50, info = {} },
			{ name = "mountain_dew", price = 2, amount = 50, info = {} },
			{ name = "gatorade_fierce_grape", price = 4, amount = 50, info = {} },
			{ name = "gatorade_strawberry_lemonade", price = 4, amount = 50, info = {} },
			{ name = "gatorade_fierce_blue_cherry", price = 4, amount = 50, info = {} },
			{ name = "gatorade_frost_glacier_cherry", price = 4, amount = 50, info = {} },
			{ name = "gatorade_fierce_grape", price = 4, amount = 50, info = {} },
			{ name = "gatorade_lime_cucumber", price = 4, amount = 50, info = {} },
			{ name = "sprite", price = 2, amount = 2, info = {} },
			{ name = "red_bull_red_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_pear_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_peach_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_coconut_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_blue_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_green_edition", price = 6, amount = 50, info = {} },
			{ name = "red_bull_orange_edition", price = 6, amount = 50, info = {} },
			{ name = "hershey_bar", price = 2, amount = 2, info = {} },
			{ name = "whoopers", price = 2, amount = 2, info = {} },
        	{ name = "crunch", price = 2, amount = 2, info = {} },
			{ name = "kit_kat", price = 2, amount = 2, info = {} },
			{ name = "nerds", price = 2, amount = 2, info = {} },
			{ name = "stickynotepad", price = 5, amount = 50, info = {} },			
		},
		["pdarmory"] = {
			{ name = "weapon_pistol", price = 0, amount = 1, info = {} },
			{ name = "weapon_stungun", price = 0, amount = 1, info = {} },
			{ name = "weapon_pumpshotgun", price = 0, amount = 1, info = {} },
			{ name = "weapon_smg", price = 0, amount = 0, info = {} },
			{ name = "weapon_carbinerifle", price = 0, amount = 1, info = {} },
			{ name = "weapon_scarh", price = 0, amount = 1, info = {} },
			{ name = "weapon_glock17", price = 0, amount = 1, info = {} },
			{ name = "weapon_m4", price = 0, amount = 1, info = {} },
			{ name = "weapon_ar15", price = 0, amount = 1, info = {} },
			{ name = "weapon_mp9", price = 0, amount = 1, info = {} },
			{ name = "weapon_mk14", price = 0, amount = 1, info = {} },
			{ name = "weapon_nightstick", price = 0, amount = 1, info = {} },
			{ name = "pistol_ammo", price = 0, amount = 5, info = {} },
			{ name = "smg_ammo", price = 0, amount = 5, info = {} },
			{ name = "snp_ammo", price = 0, amount = 5, info = {} },
			{ name = "shotgun_ammo", price = 0, amount = 5, info = {} },
			{ name = "rifle_ammo", price = 0, amount = 5, info = {} },
			{ name = "handcuffs", price = 0, amount = 5, info = {} },
			{ name = "weapon_flashlight", price = 0, amount = 1, info = {} },
			{ name = "uvlight", price = 0, amount = 1, info = {} },
			{ name = "empty_evidence_bag", price = 0, amount = 50, info = {} },
        	{ name = "police_stormram", price = 0, amount = 5 , info = {} },
			{ name = "armor", price = 0, amount = 10, info = {} },
			{ name = "heavyarmor", price = 0, amount = 10, info = {} },
			{ name = "ifak", price = 10, amount = 100, info = {} },
			{ name = "medikit", price = 10, amount = 10, info = {} },
			{ name = "defib", price = 10, amount = 10, info = {} },
			{ name = "radio", price = 0, amount = 1, info = {} },
			{ name = "policegunrack", price = 0, amount = 1, info = {} },
			{ name = "drone", price = 0, amount = 1, info = {} },			
			{ name = "pistol_flashlight", price = 0, amount = 1, info = {} },	
			{ name = "rifle_flashlight", price = 0, amount = 1, info = {} },
			{ name = "sniper_scope", price = 0, amount = 1, info = {} },
			{ name = "snipermax_scope", price = 0, amount = 1, info = {} },			
		},
		["tuner"] = {
			{ name = "harness", price = 125, amount = 100, info = {} },
			{ name = "cleaningkit", price = 25, amount = 100, info = {} },
			{ name = "nitrous", price = 150, amount = 100, info = {} },
			{ name = "advancedrepairkit", price = 25, amount = 100, info = {} },
			{ name = "driftkit", price = 5000, amount = 1, info = {} },
			{ name = "stickynotepad", price = 5, amount = 50, info = {} },
		},
		["liquor"] = {
			{ name = "bud_light", price = 5, amount = 50, info = {} },
			{ name = "coors_light", price = 5, amount = 50, info = {} },
			{ name = "modelo", price = 5, amount = 50, info = {} },
			{ name = "heineken", price = 5, amount = 50, info = {} },
			{ name = "budweiser", price = 5, amount = 50, info = {} },
			{ name = "michelob", price = 5, amount = 50, info = {} },
			{ name = "snow_beer", price = 3, amount = 50, info = {} },
			{ name = "tsingtao", price = 3, amount = 50, info = {} },
			{ name = "harbin", price = 3, amount = 50, info = {} },
			{ name = "corona", price = 5, amount = 50, info = {} },
			{ name = "guinness", price = 5, amount = 50, info = {} },
			{ name = "brew_dog", price = 3, amount = 50, info = {} },
			{ name = "yosemite_road_chardonnay", price = 8, amount = 50, info = {} },
			{ name = "white_claw_black_cherry", price = 5, amount =50, info = {} },
			{ name = "white_claw_mango", price = 5, amount = 50, info = {} },
			{ name = "white_claw_watermelon", price = 5, amount = 50, info = {} },
			{ name = "white_claw_natural_lime", price = 5, amount = 50, info = {} },
			{ name = "white_claw_ruby_grapefruit", price = 5, amount = 50, info = {} },
			{ name = "white_claw_raspberry", price = 5, amount = 50, info = {} },
			{ name = "white_claw_lemon", price = 5, amount = 50, info = {} },		
			{ name = "white_claw_tangerine", price = 5, amount = 50, info = {} },
			{ name = "truly_hard_seltzer_strawberry", price = 5, amount = 50, info = {} },
			{ name = "truly_hard_seltzer_pineapple", price = 5, amount = 50, info = {} },
			{ name = "truly_hard_seltzer_cherry", price = 5, amount = 50, info = {} },
			{ name = "truly_hard_seltzer_lime", price = 5, amount = 50, info = {} },
			{ name = "truly_hard_seltzer_lemon", price = 5, amount = 50, info = {} },
			{ name = "truly_hard_seltzer_watermelon", price = 5, amount = 50, info = {} },
			{ name = "yosemite_road_cabernet_sauvignon", price = 8, amount = 50, info = {} },
			{ name = "skol", price = 10, amount = 50, info = {} },
			{ name = "aperol", price = 10, amount = 50, info = {} },
			{ name = "jagermeister", price = 10, amount = 50, info = {} },
			{ name = "stickynotepad", price = 5, amount = 50, info = {} },
			{ name = "cups", price = 500, amount = 1, info = {} },
		},
		["electronics"] = {
			{ name = "phone", price = 500, amount = 1, info = {} },
			{ name = "radio", price = 100, amount = 1, info = {} },
			{ name = "binoculars", price = 150, amount = 50, info = {} },
			{ name = "fitbit", price = 1500, amount = 1, info = {} },
			{ name = "stickynotepad", price = 5, amount = 50, info = {} },
			{ name = "boombox", price = 1500, amount = 10, info = {} },
			{ name = "skateboard", price = 2500, amount = 10, info = {} },
		},
		["tobacco"] = {
			{ name = "cubancigar", price = 500, amount = 50, info = {} },
			{ name = "davidoffcigar", price = 500, amount = 50, info = {} },
			{ name = "redw", price = 4000, amount = 50, info = {} },
			{ name = "marlboro", price = 4500, amount = 50, info = {} },
			{ name = "redwcig", price = 150, amount = 50, info = {} },
			{ name = "marlborocig", price = 250, amount = 50, info = {} },
			{ name = "vape", price = 1200, amount = 50, info = {} },
			{ name = "lighter", price = 100, amount = 50, info = {} },
			{ name = "liquid", price = 1000, amount = 50, info = {} },
		},
		["blackmarket"] = {
			{ name = "stolencard", price = 100, amount = 50, info = {} },
			{ name = "decryptor", price = 5000, amount = 50, info = {} },
			{ name = "safecracker", price = 1000, amount = 1, info = {} },
			{ name = "boostinglaptop", price = 10000, amount = 1, info = {} },
			{ name = "boostingdisabler", price = 12000, amount = 1, info = {} },
		},
		["petshop"] = {
			{ name = "firstaidforpet", price = 200, amount = 1000, info = {} },
			{ name = "petgroomingkit", price = 500, amount = 1, info = {} },
			{ name = "collarpet", price = 8000, amount = 1, info = {} },
			{ name = "petnametag", price = 8000, amount = 1, info = {} },
			{ name = "keepcompanionrabbit", price = 2000, amount = 1, info = {} },
			{ name = "keepcompanionhen", price = 2000, amount = 1, info = {} },
			{ name = "keepcompanioncoyote", price = 4000, amount = 1, info = {} },
			{ name = "keepcompanioncat", price = 5000, amount = 1, info = {} },
			{ name = "keepcompanionwesty", price = 8000, amount = 1, info = {} },
			{ name = "keepcompanionshepherd", price = 8000, amount = 1, info = {} },
			{ name = "keepcompanionretriever", price = 8000, amount = 1, info = {} },
			{ name = "keepcompanionrottweiler", price = 8000, amount = 1, info = {} },
			{ name = "keepcompanionpug", price = 8000, amount = 1, info = {} },
			{ name = "keepcompanionpoodle", price = 8000, amount = 1, info = {} },
			{ name = "keepcompanionhusky", price = 8000, amount = 1, info = {} },
			{ name = "keepcompanionmtlion2", price = 10000, amount = 1, info = {} },
			{ name = "keepcompanionmtlion", price = 10000, amount = 1, info = {} },
		},
		["meth"] = {
			{ name = "methkey", price = 15000, amount = 1, info = {} },	
		},
		["coke"] = {
			{ name = "trimming_scissors", price = 500, amount = 1000, info = {} },
			{ name = "bakingsoda", price = 200, amount = 1000, info = {} },
			{ name = "finescale", price = 5000, amount = 1, info = {} },
			{ name = "cocainekey", price = 10000, amount = 1, info = {} },					
		},
		["rosin"] = {
			{ name = "rosincontainer", price = 200, amount = 1000, info = {} },
			{ name = "weedfilterbag", price = 200, amount = 1000, info = {} },					
		},
		["tyler"] = {
			{ name = "arketamine", price = 600, amount = 300, info = {} },
			{ name = "esketamine", price = 820, amount = 200, info = {} },			
		},
		["ray"] = {
			{ name = "opiumflower", price = 1500, amount = 350, info = {} },		
		},
		["shane"] = {
			{ name = "ayahuasca", price = 900, amount = 550, info = {} },		
		},
		["robby"] = {
			{ name = "cocaine_processing_table", price = 1500, amount = 1, info = {} },		
		},
		["marco"] = {
			{ name = "weed_white-widow_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_lemonhaze_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_skunk_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_og-kush_seed", price = 10000, amount = 1000, info = {} },	
		},
		["eric"] = {
			{ name = "weed_ak47_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_sour_diesel_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_velvet_runtz_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_cheese_seed", price = 1000, amount = 1000, info = {} },
			{ name = "weed_sour_diesel_seed", price = 1000, amount = 1000, info = {} },
		},
		["ryan"] = {
			{ name = "weed_trainwreck_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_gelato_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_blue_dream_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_pineapple_express_seed", price = 1000, amount = 1000, info = {} },
		},
		["jorge"] = {
			{ name = "weed_girl_scout_cookies_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_cherry_pie_seed", price = 400, amount = 1000, info = {} },
			{ name = "weed_lv_pk_seed", price = 1000, amount = 1000, info = {} },
			{ name = "weed_purple-haze_seed", price = 400, amount = 1000, info = {} },
		},
		["fakeplates"] = {
			{ name = "license_plate", price = 200, amount = 100, info = {} },
			{ name = "fake_plate", price = 1500, amount = 100, info = {} },
		},
		["popspills"] = {
			{ name = "bandage", price = 100, amount = 1000, info = {} },
			{ name = "ifak", price = 500, amount = 1000, info = {} },
			{ name = "painkillers", price = 200, amount = 1000, info = {} },
			{ name = "walkstick", price = 1000, amount = 1000, info = {} },
			{ name = "condom", price = 10, amount = 1000, info = {} },
			{ name = "mifepristone", price = 10, amount = 1000, info = {} },
			{ name = "testpack", price = 10, amount = 1000, info = {} },
		},
		["vanillaunicorn"] = {
			{ name = "nachos", price = 2, amount = 100, info = {} },
			{ name = "lettuce", price = 2, amount = 100, info = {} },
			{ name = "cheddar", price = 2, amount = 100, info = {} },
			{ name = "meat", price = 2, amount = 100, info = {} },
			{ name = "crisps", price = 2, amount = 100, info = {} },
			{ name = "potato", price = 2, amount = 100, info = {} },			
		},
		["beanmachine"] = {
			{ name = "water_bottle", price = 2, amount = 100, info = {} },
			{ name = "beancoffee", price = 2, amount = 100, info = {} },
			{ name = "rhinohorn", price = 2, amount = 100, info = {} },
			{ name = "oystershell", price = 2, amount = 100, info = {} },
			{ name = "sugar", price = 2, amount = 100, info = {} },
			{ name = "orange", price = 2, amount = 100, info = {} },
			{ name = "milk", price = 2, amount = 100, info = {} },
			{ name = "chickenbreast", price = 2, amount = 100, info = {} },
			{ name = "plastic", price = 2, amount = 100, info = {} },
			{ name = "tosti", price = 2, amount = 100, info = {} },
			{ name = "cheesecake", price = 2, amount = 100, info = {} },
			{ name = "watermelon", price = 2, amount = 100, info = {} },
			{ name = "crisps", price = 2, amount = 100, info = {} },
			{ name = "chocolate", price = 1, amount = 100, info = {} },
		},
		["burgershot"] = {
			{ name = "potato", price = 2, amount = 100, info = {} },
			{ name = "icecream", price = 2, amount = 100, info = {} },
			{ name = "milk", price = 2, amount = 100, info = {} },
			{ name = "lettuce", price = 2, amount = 100, info = {} },
			{ name = "onion", price = 2, amount = 100, info = {} },
			{ name = "frozennugget", price = 2, amount = 100, info = {} },
			{ name = "cheddar", price = 2, amount = 100, info = {} },
			{ name = "burgerbun", price = 2, amount = 100, info = {} },
			{ name = "burgerpatty", price = 2, amount = 100, info = {} },
		},
		["billiards"] = {
			{ name = "steakpie", price = 3, amount = 100, info = {} },
			{ name = "chickenpie", price = 3, amount = 100, info = {} },
			{ name = "meatpie", price = 3, amount = 100, info = {} },
			{ name = "cheesepie", price = 3, amount = 100, info = {} },
			{ name = "mwburger", price = 3, amount = 100, info = {} },
			{ name = "mwcburger", price = 3, amount = 100, info = {} },
			{ name = "mwbcburger", price = 3, amount = 100, info = {} },
		},
		["vanillaliquor"] = {
			{ name = "cubasil", price = 1, amount = 100, info = {} },
			{ name = "mintleaf", price = 1, amount = 100, info = {} },
			{ name = "peach", price = 2, amount = 100, info = {} },
			{ name = "strawberry", price = 2, amount = 100, info = {} },
			{ name = "orange", price = 2, amount = 100, info = {} },
			{ name = "lime", price = 2, amount = 100, info = {} },
			{ name = "lemon", price = 2, amount = 100, info = {} },
			{ name = "chocolate", price = 1, amount = 100, info = {} },
			{ name = "midori", price = 2, amount = 100, info = {} },
			{ name = "pinejuice", price = 2, amount = 100, info = {} },
			{ name = "cranberry", price = 2, amount = 100, info = {} },
			{ name = "triplsec", price = 2, amount = 100, info = {} },
			{ name = "prosecco", price = 2, amount = 100, info = {} },
			{ name = "tequila", price = 2, amount = 100, info = {} },
			{ name = "gin", price = 2, amount = 100, info = {} },
			{ name = "rum", price = 2, amount = 100, info = {} },
			{ name = "amaretto", price = 2, amount = 100, info = {} },
			{ name = "vodka", price = 2, amount = 100, info = {} },
		},
		["billiardsliquor"] = {
			{ name = "cherry", price = 2, amount = 100, info = {} },
			{ name = "lime", price = 2, amount = 100, info = {} },
			{ name = "lemon", price = 2, amount = 100, info = {} },
			{ name = "pineapple", price = 2, amount = 100, info = {} },
			{ name = "coconut", price = 2, amount = 100, info = {} },
			{ name = "cranberry", price = 2, amount = 100, info = {} },
			{ name = "apple", price = 2, amount = 100, info = {} },
			{ name = "tomato", price = 2, amount = 100, info = {} },
			{ name = "orange", price = 2, amount = 100, info = {} },
			{ name = "chardonnay", price = 3, amount = 100, info = {} },
			{ name = "barolo", price = 3, amount = 100, info = {} },
			{ name = "pinotgrigio", price = 3, amount = 100, info = {} },
			{ name = "pinotnoir", price = 3, amount = 100, info = {} },
			
		},
		["vending"] = {
			{ name = "water_bottle", price = 100, amount = 25, },
			{ name = "kurkakola", price = 100, amount = 25, },
			{ name = "sprunk", price = 100, amount = 25, },
			{ name = "sprunklight", price = 100, amount = 25, },
			{ name = "ecola", price = 100, amount = 25, },
			{ name = "ecolalight", price = 100, amount = 25, },
			{ name = "twerks_candy", price = 100, amount = 25, },
			{ name = "snikkel_candy", price = 100, amount = 25, },
		},
	},
}

Config.Locations = {
    -- 24/7 Locations
    ["247supermarket"] = {
        ["label"] = "24/7 Supermarket",
		["type"] = "items",
		["model"] = {
			`mp_m_shopkeep_01`,
			`S_F_Y_Shop_LOW`,
			`S_F_Y_SweatShop_01`,
		},
		["killable"] = true,
		["logo"] = "https://i.imgur.com/bPcM0TM.png",
        ["coords"] = {
			vector4(24.5, -1346.19, 29.5, 266.78),
			vector4(-3039.91, 584.26, 7.91, 16.79),
			vector4(-3243.27, 1000.1, 12.83, 358.73),
			vector4(1728.28, 6416.03, 35.04, 242.45),
			vector4(1697.96, 4923.04, 42.06, 326.61),
			vector4(1959.6, 3740.93, 32.34, 296.84),
			vector4(549.16, 2670.35, 42.16, 92.53),
			vector4(2677.41, 3279.8, 55.24, 334.16),
			vector4(2556.19, 380.89, 108.62, 355.58),
			vector4(372.82, 327.3, 103.57, 255.46),
			vector4(161.21, 6642.32, 31.61, 223.57),
		},
        ["products"] = Config.Products["normal"],
        ["blipsprite"] = 628,
		["blipcolour"] = 2,
    },
    -- LTD Gasoline Locations
    ["ltdgasoline"] = {
        ["label"] = "LTD Gasoline",
		["type"] = "items",
		["model"] = {
			`s_m_m_autoshop_02`,
			`S_F_M_Autoshop_01`,
			`S_M_M_AutoShop_01`,
			`S_M_M_Autoshop_03`,
			`IG_Benny`,
			`IG_Benny_02`,
			`MP_F_BennyMech_01`,
		},
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/7/72/LTD-GTAO-LSTunersBanner.png",
        ["coords"] = {
			vector4(-47.42, -1758.67, 29.42, 47.26),
			vector4(-706.17, -914.64, 19.22, 88.77),
			vector4(-1819.53, 793.49, 138.09, 131.46),
			vector4(1164.82, -323.66, 69.21, 106.86),
		},
        ["products"] = Config.Products["normal"],
        ["blipsprite"] = 628,
		["blipcolour"] = 5,
    },
    -- Rob's Liquor Locations
    ["liquor"] = {
        ["label"] = "Liquor Store",
		["type"] = "items",
		["model"] = {
			`cs_nervousron`,
			`IG_RussianDrunk`,
			`U_M_Y_MilitaryBum`,
			`A_F_M_TrampBeac_01`,
			`A_M_M_Tramp_01`,
		},
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/d/de/RebsLiquor-GTAV.png",
        ["coords"] = {
			vector4(-1221.38, -907.89, 12.33, 27.51),
			vector4(-1486.82, -377.48, 40.16, 130.89),
			vector4(-2966.41, 391.62, 15.04, 87.82),
			vector4(1165.15, 2710.78, 38.16, 177.96),
			vector4(1134.3, -983.26, 46.42, 276.3),
		},
        ["products"] = Config.Products["liquor"],
        ["blipsprite"] = 93,
		["blipcolour"] = 31,
    },
    -- Hardware Store Locations
    ["hardware"] = {
        ["label"] = "Hardware Store",
		["type"] = "items",
		["model"] = {
			`s_m_m_autoshop_02`,
			`S_F_M_Autoshop_01`,
			`S_M_M_AutoShop_01`,
			`S_M_M_Autoshop_03`,
			`IG_Benny`,
			`IG_Benny_02`,
			`MP_F_BennyMech_01`,
		},
		["coords"] = {
			vector4(46.52, -1749.55, 29.64, 50.82),
			vector4(2747.76, 3472.9, 55.67, 243.88),
			vector4(-421.65, 6135.97, 31.88, 232.98),
		},
        ["products"] = Config.Products["hardware"],
        ["blipsprite"] = 402,
		["blipcolour"] = 5,
    },
	-- Ammunation VANILLA Locations
    ["ammunation"] = {
        ["label"] = "Ammunation",
        ["targetLabel"] = "Open Ammunation",
		["type"] = "weapons",
		["model"] = {
			`s_m_m_ammucountry`,
			`S_M_Y_AmmuCity_01`,
			`MP_M_WareMech_01`,
			`A_M_M_Farmer_01`,
			`MP_M_ExArmy_01`,
			`S_M_Y_ArmyMech_01`,
			`S_M_M_Armoured_02`,
		},
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/a/aa/Ammunation-GTAV.png",
        ["coords"] = {
            vector4(808.94, -2158.99, 29.62, 330.26),
            vector4(-660.98, -933.6, 21.83, 154.74),
			vector4(1693.16, 3761.94, 34.71, 189.83),
            vector4(-330.72, 6085.81, 31.45, 190.52),
			vector4(253.41, -51.67, 69.94, 28.88),
			vector4(23.69, -1105.95, 29.8, 124.58),
            vector4(2566.81, 292.54, 108.73, 320.09),
            vector4(-1118.19, 2700.5, 18.55, 185.31),
            vector4(841.31, -1035.28, 28.19, 334.27),
			vector4(-1304.44, -395.68, 36.7, 41.85),
		},
        ["products"] = Config.Products["weapons"],
        ["blipsprite"] = 567,
		["blipcolour"] = 1,
    },
    -- Tuner 
	    ["tuner"] = {
		["label"] = "Tuner Store",
		["type"] = "items",
		["model"] = {
			`s_m_m_autoshop_02`,
			`S_F_M_Autoshop_01`,
			`S_M_M_AutoShop_01`,
			`S_M_M_Autoshop_03`,
			`IG_Benny`,
			`IG_Benny_02`,
			`MP_F_BennyMech_01`,
		},
		["coords"] = { vector4(152.15, -3007.41, 7.04, 176.15), },
		["products"] = Config.Products["tuner"],
		["blipsprite"] = 496,
		["blipcolour"] = 2,
		["hideblip"] = true,
	},
    -- PD Shop
    ["pdshop"] = {
		["label"] = "PD Cafe",
		["type"] = "items",
		["job"] = "police",
		["model"] = {
			`A_F_Y_Hipster_02`,
		},
		["coords"] = { vector4(462.44, -982.69, 30.69, 43.92), },
		["products"] = Config.Products["pdshop"],
		["blipsprite"] = 52,
		["blipcolour"] = 31,
		["hideblip"] = true,
    },
	  -- PD Shop
    ["pdarmory"] = {
		["label"] = "PD Cafe",
		["type"] = "items",
		["job"] = "police",
		["model"] = {
			`s_m_m_fiboffice_01`,
		},
		["coords"] = { vector4(482.6, -995.65, 30.69, 173.8), },
		["products"] = Config.Products["pdarmory"],
		["blipsprite"] = 52,
		["blipcolour"] = 31,
		["hideblip"] = true,
    },
    -- Leisure Shop Locations
    ["leisureshop"] = {
		["label"] = "Leisure Shop",
		["type"] = "items",
		["model"] = {
			`mp_m_boatstaff_01`,
			`a_m_y_beach_01`,
		},
		["coords"] = { vector4(-1505.67, 1512.29, 115.29, 244.94) },
		["products"] = Config.Products["leisureshop"],
		["blipsprite"] = 52,
		["blipcolour"] = 2,
    },
    -- Local Store Locations
    ["liquor"] = {
        ["label"] = "Liquor Store",
		["type"] = "items",
		["model"] = {
			`cs_nervousron`,
			`IG_RussianDrunk`,
			`U_M_Y_MilitaryBum`,
			`A_F_M_TrampBeac_01`,
			`A_M_M_Tramp_01`,
		},
        ["coords"] = { vector4(-160.54, 6320.85, 31.59, 317.79), },
        ["products"] = Config.Products["liquor"],
        ["blipsprite"] = 52,
		["blipcolour"] = 2,
    },
	["digitalden"] = {
		["label"] = "Digital Den",
		["type"] = "items",
		["model"] = {
			`S_M_M_LifeInvad_01`,
			`IG_Ramp_Hipster`,
			`A_M_Y_Hipster_02`,
			`A_F_Y_Hipster_01`,
			`IG_LifeInvad_01`,
			`IG_LifeInvad_02`,
			`CS_LifeInvad_01`,
		},
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/b/b5/DigitalDen-GTAV-Logo.png",
		["coords"] = {
		vector4(1132.44, -474.31, 66.72, 343.74),
		vector4(-1271.58, -1411.6, 4.37, 123.02),
		vector4(-1232.16, -1439.76, 4.37, 213.0),
			},
		["products"] = Config.Products["electronics"],
		["blipsprite"] = 606,
		["blipcolour"] = 7,
	},
	["Tobacco"] = {
		["label"] = "Tobacco Store",
		["type"] = "items",
		["model"] = {
		`a_m_m_og_boss_01`,
		},
		["coords"] = { 
		vector4(-1249.66, -1449.72, 4.37, 33.4),
		vector4(-1211.4, -1464.31, 4.37, 301.3),
		vector4(-1221.73, -1490.24, 4.37, 33.82),		
		},
		["products"] = Config.Products["tobacco"],
		["blipsprite"] = 59,
		["blipcolour"] = 2,
		["hideblip"] = false,
	},
	["blackmarket"] = {
		["label"] = "Black Market",
		["type"] = "items",
		["model"] = {
			`mp_f_weed_01`,
			`MP_M_Weed_01`,
			`A_M_Y_MethHead_01`,
			`A_F_Y_RurMeth_01`,
			`A_M_M_RurMeth_01`,
			`MP_F_Meth_01`,
			`MP_M_Meth_01`,
		},
		["coords"] = { vector4(576.31, 2790.38, 42.2, 24.69), },
		["products"] = Config.Products["blackmarket"],
		["hideblip"] = true,
	},
	["fakeplates"] = {
		["label"] = "Black Market",
		["type"] = "items",
		["model"] = {
			`A_M_Y_Hipster_02`,
			`A_F_Y_Hipster_01`,
		},
		["coords"] = { vector4(-64.67, 78.13, 71.61, 56.05), },
		["products"] = Config.Products["fakeplates"],
		["hideblip"] = true,
	},
	--keep companion
	["petshop"] = {
		["label"] = "Pet Shop",
		["type"] = "items",
		["model"] = {
			`S_M_M_StrVend_01`,
			`mp_m_shopkeep_01`,
			`a_f_y_hipster_03`,
		},
		["coords"] = { 
			vector4(562.44, 2741.2, 42.87, 192.56),
			vector4(-269.68, 6283.39, 31.48, 225.54),
			},
		["products"] = Config.Products["petshop"],
		["blipsprite"] = 273,
		["blipcolour"] = 0,
		["hideblip"] = false,
	},
	["jewelry"] = {
		["label"] = "Jewelry Shop",
		["type"] = "items",
		["model"] = {
			`a_m_y_business_01`,
			`a_m_y_business_02`,
			`a_m_y_business_03`,
		},
		["coords"] = { 
			vector4(-636.51, -251.74, 38.49, 309.51),
			},
		["products"] = Config.Products["jewelry"],
		["blipsprite"] = 617,
		["blipcolour"] = 23,
		["hideblip"] = false,
	},
	--blackmarket meth
	["meth"] = {
		["label"] = "Black Market Supplies",
		["type"] = "items",
		["model"] = {
			`mp_f_weed_01`,
			`MP_M_Weed_01`,
			`A_M_Y_MethHead_01`,
			`A_F_Y_RurMeth_01`,
			`A_M_M_RurMeth_01`,
			`MP_F_Meth_01`,
			`MP_M_Meth_01`,
		},
		["coords"] = {vector4(2076.77, 1700.09, 103.07, 358.24) },
		["products"] = Config.Products["meth"],
		["blipsprite"] = 273,
		["blipcolour"] = 0,
		["hideblip"] = true,
	},
	--blackmarket coke
	["coke"] = {
		["label"] = "Black Market Supplies",
		["type"] = "items",
		["model"] = {
			`mp_f_weed_01`,
			`MP_M_Weed_01`,
			`A_M_Y_MethHead_01`,
			`A_F_Y_RurMeth_01`,
			`A_M_M_RurMeth_01`,
			`MP_F_Meth_01`,
			`MP_M_Meth_01`,
		},
		["coords"] = { vector4(552.51, -166.38, 54.48, 268.08) },
		["products"] = Config.Products["coke"],
		["blipsprite"] = 273,
		["blipcolour"] = 0,
		["hideblip"] = true,
	},
	--blackmarket rosin
	["rosin"] = {
		["label"] = "Black Market Supplies",
		["type"] = "items",
		["model"] = {
			`mp_f_weed_01`,
			`MP_M_Weed_01`,
			`A_M_Y_MethHead_01`,
			`A_F_Y_RurMeth_01`,
			`A_M_M_RurMeth_01`,
			`MP_F_Meth_01`,
			`MP_M_Meth_01`,
		},
		["coords"] = { vector4(1558.96, 3601.01, 38.78, 121.28) },
		["products"] = Config.Products["rosin"],
		["blipsprite"] = 273,
		["blipcolour"] = 0,
		["hideblip"] = true,
	},
	--tyler the dealer
	["tyler"] = {
		["label"] = "Tyler",
		["type"] = "items",
		["model"] = {
			`a_m_o_beach_01`,
		},
		["coords"] = { 
		vector4(-2196.95, -404.3, 9.8, 78.5),
		},
		["products"] = Config.Products["tyler"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
 },	
  	--Ray the dealer
	["ray"] = {
		["label"] = "Ray",
		["type"] = "items",
		["model"] = {
			`cs_fabien`,
		},
		["coords"] = { 
		vector4(912.3832, -1705.1648, 38.4704, 253.1773),
		},
		["products"] = Config.Products["ray"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
 },
   	--shane the dealer
	["shane"] = {
		["label"] = "Shane",
		["type"] = "items",
		["model"] = {
			`a_m_y_latino_01`,
		},
		["coords"] = { 
		vector4(2818.8643, -742.0105, 2.4068, 280.8259),
		},
		["products"] = Config.Products["shane"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
 },
 --Robby the dealer
	["robby"] = {
		["label"] = "Robby",
		["type"] = "items",
		["model"] = {
			`s_m_y_xmech_02`,
		},
		["coords"] = { 
		vector4(722.9755, 4190.2534, 41.0929, 183.8476),
		},
		["products"] = Config.Products["robby"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
 },
  --marco the dealer tier 1
	["marco"] = {
		["label"] = "Marco",
		["type"] = "items",
		["model"] = {
			`ig_cletus`,
		},
		["coords"] = { 
		vector4(291.5420, 110.7993, 125.7343, 69.5562),
		},
		["products"] = Config.Products["marco"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
 },
   --ryan the dealer tier 3
	["ryan"] = {
		["label"] = "Ryan",
		["type"] = "items",
		["model"] = {
			`ig_djblamrupert`,
		},
		["coords"] = { 
		vector4(2629.9604, 2934.0222, 44.7390, 270.7939),
		},
		["products"] = Config.Products["ryan"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
 },
   --jorge the dealer tier 4
	["jorge"] = {
		["label"] = "Jorge",
		["type"] = "items",
		["model"] = {
			`ig_djsoljakob`,
		},
		["coords"] = { 
		vector4(-90.47, 4583.03, 99.1, 212.88),
		},
		["products"] = Config.Products["jorge"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
 },
   --Eric the dealer tier 2
	["eric"] = {
		["label"] = "Eric",
		["type"] = "items",
		["model"] = {
			`ig_djblamrupert`,
		},
		["coords"] = { 
		vector4(-2186.51, 209.8, 194.6, 108.47),
		},
		["products"] = Config.Products["eric"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
 },
	--Pops Pills
	["popspills"] = {
		["label"] = "Pops Pills",
		["type"] = "items",
		["model"] = {
			`s_f_y_scrubs_01`,
			`s_m_m_doctor_01`,
			`s_m_m_scientist_01`,
			`s_m_y_autopsy_01`,
		},
		["coords"] = { 
		vector4(-1253.94, -1436.72, 4.37, 127.79),
		vector4(-1198.58, -1460.2, 4.37, 30.95),
		vector4(-1225.58, -1477.22, 4.37, 136.51),
		},
		["products"] = Config.Products["popspills"],
		["blipsprite"] = 51,
		["blipcolour"] = 0,
		["hideblip"] = true,
	},
	["vanillaunicorn"] = { -- start job shops
		["label"] = "Vanilla Unicorn Food Shop",
		["type"] = "items",
		["job"] = "vanilla",
		["model"] = {
			`ig_old_man2`,
			`ig_oneil`,
			`ig_hunter`,
			`ig_chef`,
		},
		["coords"] = {
			vector4(-1253.48, -1444.57, 4.37, 32.18),
		},
		["products"] = Config.Products["vanillaunicorn"], 
		["hideblip"] = true,
	},
	["beanmachine"] = {
		["label"] = "Bean Machine Food Shop",
		["type"] = "items",
		["job"] = "beanmachine",
		["model"] = {
			`ig_old_man2`,
			`ig_oneil`,
			`ig_hunter`,
			`ig_chef`,
		},
		["coords"] = {
			vector4(-1206.08, -1460.57, 4.37, 305.06),
		},
		["products"] = Config.Products["beanmachine"], 
		["hideblip"] = true,
	},
	["burgershot"] = {
		["label"] = "Burgershot Food Shop",
		["type"] = "items",
		["job"] = "burgershot",
		["model"] = {
			`ig_old_man2`,
			`ig_oneil`,
			`ig_hunter`,
			`ig_chef`,
		},
		["coords"] = {
			vector4(-1225.35, -1484.84, 4.37, 37.1),
		},
		["products"] = Config.Products["burgershot"], 
		["hideblip"] = true,
	},
	["billiards"] = {
		["label"] = "Red Tails Food Shop",
		["type"] = "items",
		["job"] = "billiards",
		["model"] = {
			`ig_old_man2`,
			`ig_oneil`,
			`ig_hunter`,
			`ig_chef`,
		},
		["coords"] = {
			vector4(-1251.52, -1438.9, 4.37, 123.01),
		},
		["products"] = Config.Products["billiards"], 
		["hideblip"] = true,
	},
	["billiardsliquor"] = {
		["label"] = "Red Tails Liquor Shop",
		["type"] = "items",
		["job"] = "billiards",
		["model"] = {
			`ig_old_man2`,
			`ig_oneil`,
			`ig_hunter`,
			`ig_chef`,
		},
		["coords"] = {
			vector4(-1271.17, -1418.0, 4.37, 40.06),
		},
		["products"] = Config.Products["billiardsliquor"], 
		["hideblip"] = true,
	},
	["vanillaliquor"] = {
		["label"] = "Vanilla Unicorn Liquor Shop",
		["type"] = "items",
		["job"] = "vanilla",
		["model"] = {
			`ig_old_man2`,
			`ig_oneil`,
			`ig_hunter`,
			`ig_chef`,
		},
		["coords"] = {
			vector4(-1225.64, -1439.11, 4.37, 130.72),
		},
		["products"] = Config.Products["vanillaliquor"], 
		["hideblip"] = true,
	},
}

--if Gabz locations are enabled, override their coords with these
if Config.Gabz247 then
	Config.Locations["247supermarket"]["coords"] = {
		vector4(24.91, -1346.86, 29.5, 268.37),
		vector4(-3039.64, 584.78, 7.91, 21.88),
		vector4(-3242.73, 1000.46, 12.83, 2.08),
		vector4(1728.44, 6415.4, 35.04, 243.26),
		vector4(1697.96, 4923.04, 42.06, 326.61),
		vector4(1960.26, 3740.6, 32.34, 300.45),
		vector4(548.67, 2670.94, 42.16, 101.0),
		vector4(2677.97, 3279.95, 55.24, 325.89),
		vector4(2556.8, 381.27, 108.62, 359.15),
		vector4(373.08, 326.75, 103.57, 253.14),
		vector4(161.2, 6641.74, 31.7, 221.02),
		vector4(812.86, -782.01, 26.17, 270.01),
	}
end
if Config.GabzAmmu then
	Config.Locations["ammunation"]["coords"] = {
		vector4(-659.16, -939.79, 21.83, 91.25),
		vector4(812.85, -2155.16, 29.62, 355.85),
		vector4(1698.04, 3757.43, 34.71, 136.69),
		vector4(-326.03, 6081.17, 31.45, 138.33),
		vector4(246.87, -51.3, 69.94, 335.47),
		vector4(18.71, -1108.24, 29.8, 158.71),
		vector4(2564.85, 298.83, 108.74, 283.17),
		vector4(-1112.4, 2697.08, 18.55, 152.96),
		vector4(841.16, -1028.63, 28.19, 294.2),
		vector4(-1310.71, -394.33, 36.7, 340.51),
	}
end
if Config.BlackMarket then
	Config.Locations["blackmarket"] = {
		["label"] = "Black Market",
		["type"] = "items",
		["model"] = {
			`mp_f_weed_01`,
			`MP_M_Weed_01`,
			`A_M_Y_MethHead_01`,
			`A_F_Y_RurMeth_01`,
			`A_M_M_RurMeth_01`,
			`MP_F_Meth_01`,
			`MP_M_Meth_01`,
		},
		["coords"] = {
			vector4(776.24, 4184.08, 41.8, 92.12),
			vector4(2482.51, 3722.28, 43.92, 39.98),
			vector4(462.67, -1789.16, 28.59, 317.53),
			vector4(-115.15, 6369.07, 31.52, 232.08),
			vector4(752.52, -3198.33, 6.07, 301.72)
		},
		["products"] = Config.Products["blackmarket"],
		["hideblip"] = true,
	}
end

if Config.VendOverride then
	Config.Locations["vendingmachine"] = {
		["label"] = "Vending Machine",
		["targetIcon"] = "fas fa-calculator",
		["targetLabel"] = "Vending Machine",
		["type"] = "items",
		["logo"] = "https://static.wikia.nocookie.net/gtawiki/images/d/d4/Ecola-GTAO-LSTunersBanner.png",
		["model"] = { -- You can add more models to this, but these make the most sense for the vending machine stuff
			`prop_vend_soda_01`,
			`prop_vend_soda_02`,
			`prop_vend_snak_01`,
			`prop_vend_snak_01_tu`
		},
		["coords"] = { -- If you want to place custom vending machine locations
			vector4(131.13, -3007.16, 7.04, 0.0), -- GABZ LS Tuners
		},
		["products"] = Config.Products["vending"],
	}
end
Config.ItemModels = {
	["repairkit"] = `v_ind_cs_toolbox4`,
	["advancedrepairkit"] = `v_ind_cs_toolbox4`,
	["phone"] = `p_amb_phone_01`,
	["tosti"] = `prop_sandwich_01`,
	["sandwich"] = `prop_sandwich_01`,
	["water_bottle"] = `ba_prop_club_water_bottle`,
	["kurkacola"] = `prop_ecola_can`,
	["sprunk"] = `v_res_tt_can03`,
	["sprunklight"] = `v_res_tt_can03`,
	["ecola"] = `prop_ecola_can`,
	["ecolalight"] = `prop_ecola_can`,
	["twerks_candy"] = `prop_choc_pq`,
	["snikkel_candy"] = `prop_choc_pq`,
	["beer"] = `prop_sh_beer_pissh_01`,
	["whiskey"] = `prop_whiskey_bottle`,
	["vodka"] = `prop_vodka_bottle`,
	["lighter"] = `lux_prop_lighter_luxe`,

	["screwdriverset"] = `prop_tool_screwdvr01`,
	["radio"] = `prop_cs_hand_radio`,
	["binoculars"] = `v_serv_ct_binoculars`,
	["cleaningkit"] = `prop_huf_rag_01`,

	["casinochips"] = `vw_prop_chip_100dollar_st`,
	["diving_gear"] = `p_s_scuba_tank_s`,
	["jerry_can"] = `prop_jerrycan_01a`,
	["parachute"] = `p_parachute_s_shop`,

	["coffee"] = `prop_fib_coffee`,
	["fitbit"] = `p_watch_02`,
	["radioscanner"] = `prop_police_radio_main`,
	--Weapons
	["weapon_bat"] = `p_cs_bbbat_01`,
	["weapon_knife"] = `prop_w_me_knife_01`,
	["weapon_hammer"] = `w_me_hammer`,
	["weapon_hatchet"] = `prop_w_me_hatchet`,
	['weapon_dagger'] = `prop_w_me_dagger`,
	['weapon_bottle'] = `prop_w_me_bottle`,
	['weapon_crowbar'] = `prop_ing_crowbar`,
	['weapon_flashlight'] = `w_me_flashlight`,
	['weapon_golfclub'] = `prop_golf_iron_01`,
	['weapon_knuckle'] = `w_me_knuckle`,
	['weapon_machete'] = `prop_ld_w_me_machette`,
	['weapon_switchblade'] = `w_me_switchblade`,
	['weapon_nightstick'] = `w_me_nightstick`,
	['weapon_wrench'] = `v_ind_cs_wrench`,
	['weapon_battleaxe'] = `w_me_battleaxe`,
	['weapon_poolcue'] = `w_me_poolcue`,
	['weapon_handcuffs']  = `prop_cs_cuffs_01`,
	['weapon_bread']  = `v_res_fa_bread01`,
	['weapon_stone_hatchet'] = `w_me_stonehatchet`,

	['weapon_pistol'] = `w_pi_pistol`,
	['weapon_pistol_mk2'] = `w_pi_pistolmk2`,
	['weapon_combatpistol'] = `w_pi_combatpistol`,
	['weapon_appistol']  = `w_pi_appistol`,
	['weapon_stungun'] 	 = `w_pi_stungun`,
	['weapon_pistol50']  = `w_pi_pistol50`,
	['weapon_snspistol']  = `w_pi_sns_pistol`,
	['weapon_heavypistol']  = `w_pi_heavypistol`,
	['weapon_vintagepistol'] = `w_pi_vintage_pistol`,
	['weapon_flaregun'] = `w_pi_flaregun`,
	--['weapon_marksmanpistol'] = ``,
	['weapon_revolver'] = `w_pi_revolver`,
	['weapon_revolver_mk2'] = `w_pi_revolvermk2`,
	['weapon_doubleaction'] = `w_pi_wep1_gun`,
	['weapon_snspistol_mk2'] = `w_pi_sns_pistolmk2`,
	['weapon_raypistol'] = `w_pi_raygun_ev`,
	['weapon_ceramicpistol'] = `w_pi_ceramic_pistol`,
	['weapon_navyrevolver'] = `w_pi_wep2_gun`,
	--['weapon_gadgetpistol'] = ``,
	['weapon_microsmg'] = `w_sb_microsmg`,
	['weapon_smg'] = `w_sb_smg`,
	['weapon_smg_mk2'] = `w_sb_smgmk2`,
	['weapon_assaultsmg'] = `w_sb_assaultsmg`,
	['weapon_combatpdw'] = `w_sb_pdw`,
	--['weapon_machinepistol'] = ``,
	['weapon_minismg'] = `w_sb_minismg`,
	['weapon_raycarbine'] = `w_ar_srifle`,
	['weapon_pumpshotgun'] = `w_sg_pumpshotgun`,
	['weapon_pumpshotgun_mk2'] = `w_sg_pumpshotgunmk2`,
	['weapon_sawnoffshotgun'] = `w_sg_sawnoff`,
	['weapon_assaultshotgun'] = `w_sg_assaultshotgun`,
	['weapon_bullpupshotgun'] = `w_sg_bullpupshotgun`,
	['weapon_musket'] = `w_ar_musket`,
	['weapon_heavyshotgun'] = `w_sg_heavyshotgun`,
	['weapon_dbshotgun'] = `w_sg_doublebarrel`,
	--['weapon_autoshotgun'] = ``,
	--['weapon_combatshotgun'] = ``,

	['weapon_assaultrifle'] = `w_ar_assaultrifle`,
	['weapon_assaultrifle_mk2'] = `w_ar_assaultriflemk2`,
	['weapon_carbinerifle'] = `w_ar_carbinerifle`,
	['weapon_carbinerifle_mk2'] = `w_ar_carbineriflemk2`,
	['weapon_advancedrifle'] = `w_ar_advancedrifle`,
	['weapon_specialcarbine'] = `w_ar_specialcarbine`,
	['weapon_specialcarbine_mk2'] = `w_ar_specialcarbinemk2`,
	['weapon_bullpuprifle'] = `w_ar_bullpuprifle`,
	['weapon_bullpuprifle_mk2'] = `w_ar_bullpupriflemk2`,
	['weapon_compactrifle']  = `w_ar_assaultrifle_smg`,
	['weapon_militaryrifle'] = `w_ar_heavyrifleh`,
	['weapon_mg'] = `w_mg_mg`,
	['weapon_combatmg'] = `w_mg_combatmg`,
	['weapon_combatmg_mk2'] = `w_mg_combatmgmk2`,
	['weapon_gusenberg'] = `w_sb_gusenberg`,

	['weapon_sniperrifle'] = `w_sr_sniperrifle`,
	['weapon_heavysniper'] = `w_sr_heavysniper`,
	['weapon_heavysniper_mk2'] = `w_sr_heavysnipermk2`,
	['weapon_marksmanrifle'] = `w_sr_marksmanrifle`,
	['weapon_marksmanrifle_mk2'] = `w_sr_marksmanriflemk2`,
	--['weapon_remotesniper'] = ``,
	['weapon_rpg'] = `w_lr_rpg`,
	['weapon_grenadelauncher'] = `w_lr_grenadelauncher`,
	['weapon_grenadelauncher_smoke'] = `w_lr_grenadelauncher`,
	['weapon_minigun'] = `prop_minigun_01`,
	['weapon_firework'] = `w_lr_firework`,
	['weapon_railgun'] = `w_ar_railgun`,
	--['weapon_hominglauncher'] = ``,
	--['weapon_compactlauncher'] = ``,
	--['weapon_rayminigun'] = ``,
	['weapon_grenade'] = `w_ex_grenadefrag`,
	['weapon_bzgas'] = `prop_gas_grenade`,
	['weapon_molotov'] = `w_ex_molotov`,
	--['weapon_stickybomb'] = ``,
	['weapon_proxmine'] = `gr_prop_gr_pmine_01a`,
	['weapon_snowball'] = `w_ex_snowball`,
	['weapon_pipebomb'] = `w_ex_pipebomb`,
	['weapon_ball'] = `w_am_baseball`,
	['weapon_smokegrenade'] = `w_ex_grenadesmoke`,
}