----------------------------------
--<!>-- BOII | DEVELOPMENT --<!>--
----------------------------------

-- Language settings
Language = {   
    Targeting = { 
        ['dutyicon'] = 'fas fa-clipboard', -- Icon used by qb-target for on duty location visit; https://fontawesome.com to change
        ['dutylabel'] = 'Clock In/Out', -- Label used by qb-target for on duty location
        ['bossicon'] = 'fas fa-clipboard-list', -- Icon used by qb-target for boss menu location visit; https://fontawesome.com to change
        ['bosslabel'] = 'Open Job Management', -- Label used by qb-target for boss menu location
        ['bossstorageicon'] = 'fas fa-box', -- Icon used by qb-target for boss storage locations visit; https://fontawesome.com to change
        ['bossstoragelabel'] = 'Open Management Storage', -- Label used by qb-target for boss storage locations
        ['eposicon'] = 'fas fa-cash-register', -- Icon used by qb-target for payment locations visit; https://fontawesome.com to change
        ['eposlabel'] = 'Charge Customer', -- Label used by qb-target for payment locations
        ['storeicon'] = 'fas fa-shopping-basket', -- Icon used by qb-target for job location visit; https://fontawesome.com to change
        ['storelabel'] = 'Purchase Stock', -- Label used by qb-target for store location
        ['jobstorageicon'] = 'fas fa-box', -- Icon used by qb-target for job storage locations visit; https://fontawesome.com to change
        ['jobstoragelabel'] = 'Open Storage', -- Label used by qb-target for job storage locations
        ['traystorageicon'] = 'fas fa-shopping-cart', -- Icon used by qb-target for tray storage locations visit; https://fontawesome.com to change
        ['traystoragelabel'] = 'Collect Order', -- Label used by qb-target for tray storage locations
        ['forceentryicon'] = 'fa-solid fa-unlock', -- Icon used by qb-target for force entry into storage locations visit; https://fontawesome.com to change
        ['forceentrylabel'] = 'Force Open Storage', -- Label used by qb-target for force entry into storage locations
        ['outfiticon'] = 'fas fa-shirt', -- Icon used by qb-target for wardrobe locations visit; https://fontawesome.com to change
        ['outfitlabel'] = 'Change Outfit', -- Label used by qb-target for wardrobe locations
        ['washicon'] = 'fas fa-hands-wash', -- Icon used by qb-target for washing locations visit; https://fontawesome.com to change
        ['washfacelabel'] = 'Wash Your Face', -- Label used by qb-target for washing locations  
        ['washhandslabel'] = 'Wash Your Hands', -- Label used by qb-target for washing locations
        ['washdishesicon'] = 'fas fa-sink', -- Icon used by qb-target for dishwash location visit; https://fontawesome.com to change
        ['platelabel'] = 'Wash Plate', -- Label used by qb-target for washing plates at dishwash location
        ['cuplabel'] = 'Wash Cup', -- Label used by qb-target for washing cups at dishwash location
        ['glasslabel'] = 'Wash Glass', -- Label used by qb-target for washing glasses at dishwash location
        ['pintglasslabel'] = 'Wash Pint Glass', -- Label used by qb-target for washing pintglasses at dishwash location
        ['smallglasslabel'] = 'Wash Small Glass', -- Label used by qb-target for washing small glasses at dishwash location
        ['wineglasslabel'] = 'Wash Wine Glass', -- Label used by qb-target for washing wine glasses at dishwash location
        ['cocktailglasslabel'] = 'Wash Cocktail Glass', -- Label used by qb-target for washing cocktail glasses at dishwash location
        ['peticon'] = 'fas fa-paw', -- Icon used by qb-target for snake location visit; https://fontawesome.com to change
        ['snakelabel'] = 'Feed The Snake', -- Label used by qb-target for snake location
        ['mouselabel'] = 'Take A Mouse', -- Label used by qb-target for mouse location
        ['pumpicon'] = 'fas fa-beer', -- Icon used by qb-target for pump locations visit; https://fontawesome.com to change
        ['pumplabel'] = 'Pull A Pint', -- Label used by qb-target for pump locations
        ['liquoricon'] = 'fas fa-glass-whiskey', -- Icon used by qb-target for liquor location visit; https://fontawesome.com to change
        ['whiskeylabel'] = 'Pull Whiskey', -- Label used by qb-target for whiskey location
        ['rumlabel'] = 'Pull Rum', -- Label used by qb-target for rum location 
        ['vodkalabel'] = 'Pull Vodka', -- Label used by qb-target for vodka location
        ['glassesicon'] = 'fa-solid fa-glass-water', -- Icon used by qb-target for glasses locations visit; https://fontawesome.com to change
        ['takeglasslabel'] = 'Take A Glass', -- Label used by qb-target for taking a glass from glasses locations
        ['storeglasslabel'] = 'Put Away Glass', -- Label used by qb-target for storing a glass in glasses locations
        ['takejarlabel'] = 'Take A Jar', -- Label used by qb-target for taking a jar from glasses locations
        ['storejarlabel'] = 'Put Away Jar', -- Label used by qb-target for storing a jar in glasses locations
        ['takepintglasslabel'] = 'Take A Pint Glass', -- Label used by qb-target for taking a pint glass from glasses locations
        ['storepintglasslabel'] = 'Put Away Pint Glass', -- Label used by qb-target for storing a pint glass in glasses locations
        ['takesmallglasslabel'] = 'Take A Small Glass', -- Label used by qb-target for taking a small glass from glasses locations
        ['storesmallglasslabel'] = 'Put Away Small Glass', -- Label used by qb-target for storing a small glass in glasses locations
        ['takecocktailglasslabel'] = 'Take A Cocktail Glass', -- Label used by qb-target for taking a cocktail glass from glasses locations
        ['storecocktailglasslabel'] = 'Put Away Cocktail Glass', -- Label used by qb-target for storing a cocktail glass in glasses locations
        ['takewineglasslabel'] = 'Take A Wine Glass', -- Label used by qb-target for taking a wine glass from glasses locations
        ['storewineglasslabel'] = 'Put Away Wine Glass', -- Label used by qb-target for storing a wine glass in glasses locations
        ['platesicon'] = 'fa-solid fa-earth-oceania', -- Icon used by qb-target for plates location visit; https://fontawesome.com to change
        ['takeplatelabel'] = 'Take A Plate', -- Label used by qb-target for taking a plate from plates location
        ['storeplatelabel'] = 'Put Away Plate', -- Label used by qb-target for storing a plate in plates location
        ['cupsicon'] = 'fa-solid fa-mug-hot', -- Icon used by qb-target for cups location visit; https://fontawesome.com to change
        ['takecuplabel'] = 'Take A Cup', -- Label used by qb-target for taking cup from cups location
        ['storecuplabel'] = 'Put Away Cup', -- Label used by qb-target for storing cup in cups location
        ['hotdrinksicon'] = 'fas fa-coffee', -- Icon used by qb-target for hot drinks location visit; https://fontawesome.com to change
        ['makecoffeelabel'] = 'Make A Coffee', -- Label used by qb-target making coffee at hot drinks location
        ['maketealabel'] = 'Make A Tea', -- Label used by qb-target making coffee at hot drinks location
        ['microwaveicon'] = 'fas fa-utensils', -- Icon used by qb-target for microwave location visit; https://fontawesome.com to change
        ['microwavelabel'] = 'Cook Microwave Food', -- Label used by qb-target for microwave location 
        ['cocktailsicon'] = 'fas fa-cocktail', -- Icon used by qb-target for cocktail location visit; https://fontawesome.com to change
        ['cocktailslabel'] = 'Mix Cocktails', -- Label used by qb-target for cocktail location
        ['garageicon'] = 'fas fa-car', -- Icon used by qb-target for garage location visit; https://fontawesome.com to change
        ['garagelabel'] = 'Company Vehicle', -- Label used by qb-target for garage location    
    },
    Duty = {
        ['dutymenuheader'] = 'Staff Duty', -- Menu header
        ['dutymenuheadertext'] = 'Clock in and out of duty here!', -- Menu header text
        ['dutymenuheadericon'] = 'fa-solid fa-briefcase', -- Menu header icon
        ['dutytoggle'] = '• Clock In/Out', -- Menu header
        ['dutytoggleicon'] = 'fa-solid fa-clock' -- Menu header icon
    },
    Billing = {
        ['paymenuheader'] = 'Billiards Bar', -- Menu header
        ['paymenuheadertext'] = 'Charge Customer', -- Menu header text
        ['invoicesent'] = 'Invoice sent successfully!', -- Notification
        ['invoicereceived'] = 'Invoice received from Billiards Bar!', -- Notification
        ['minamount'] = 'You cant charge someone nothing idiot..', -- Notification
        ['billself'] = 'You cant bill yourself idiot..', -- Notification
        ['billoffline'] = 'You cant bill someone whos not in city idiot..', -- Notification
        ['noaccess'] = 'You are not authorised to make sales..', -- Notification
        ['paytext'] = 'paypal id', -- Input text when charging customers
        ['payamount'] = '$ amount', -- Input text when charging customers
    },
    Wash = {
        ['washedhands'] = 'You washed your hands!', -- Notification
        ['washedface'] = 'You washed your face!', -- Notification
        ['washedplate'] = 'You washed a Plate!', -- Notification
        ['washedcup'] = 'You washed a Cup!', -- Notification
        ['washedglass'] = 'You washed a Glass!', -- Notification
        ['washedpintglass'] = 'You washed a Pint Glass!', -- Notification
        ['washedsmallglass'] = 'You washed a Small Glass!', -- Notification
        ['washedwineglass'] = 'You washed a Wine Glass!', -- Notification
        ['washedcocktailglass'] = 'You washed a Cocktail Glass!', -- Notification
        ['takeplate'] = 'You took a '..Config.Wash.Dishes.Plate.Return.label..'!', -- Notification
        ['storeplate'] = 'You stored a '..Config.Wash.Dishes.Plate.Return.label..'!', -- Notification
        ['takecup'] = 'You took a '..Config.Wash.Dishes.Cup.Return.label..'!', -- Notification
        ['storecup'] = 'You stored a '..Config.Wash.Dishes.Cup.Return.label..'!', -- Notification
        ['takeglass'] = 'You took a '..Config.Wash.Dishes.Glass.Return.label..'!', -- Notification
        ['storeglass'] = 'You stored a '..Config.Wash.Dishes.Glass.Return.label..'!', -- Notification
        ['takepintglass'] = 'You took a '..Config.Wash.Dishes.PintGlass.Return.label..'!', -- Notification
        ['storepintglass'] = 'You stored a '..Config.Wash.Dishes.PintGlass.Return.label..'!', -- Notification
        ['takewineglass'] = 'You took a '..Config.Wash.Dishes.WineGlass.Return.label..'!', -- Notification
        ['storewineglass'] = 'You stored a '..Config.Wash.Dishes.WineGlass.Return.label..'!', -- Notification
        ['takecocktailglass'] = 'You took a '..Config.Wash.Dishes.CocktailGlass.Return.label..'!', -- Notification
        ['storecocktailglass'] = 'You stored a '..Config.Wash.Dishes.CocktailGlass.Return.label..'!', -- Notification
        ['takesmallglass'] = 'You took a '..Config.Wash.Dishes.SmallGlass.Return.label..'!', -- Notification
        ['storesmallglass'] = 'You stored a '..Config.Wash.Dishes.SmallGlass.Return.label..'!', -- Notification
        ['nodirtyplate'] = 'You dont have any '..Config.Wash.Dishes.Plate.Required.label, -- Notification
        ['nodirtycup'] = 'You dont have any '..Config.Wash.Dishes.Cup.Required.label, -- Notification
        ['nodirtyglass'] = 'You dont have any '..Config.Wash.Dishes.Glass.Required.label, -- Notification
        ['nodirtypintglass'] = 'You dont have any '..Config.Wash.Dishes.PintGlass.Required.label, -- Notification
        ['nodirtysmallglass'] = 'You dont have any '..Config.Wash.Dishes.SmallGlass.Required.label, -- Notification
        ['nodirtywineglass'] = 'You dont have any '..Config.Wash.Dishes.WineGlass.Required.label, -- Notification
        ['nodirtycocktailglass'] = 'You dont have any '..Config.Wash.Dishes.CocktailGlass.Required.label, -- Notification
        ['noplate'] = 'You dont have a '..Config.Wash.Dishes.Plate.Return.label, -- Notification
        ['nocup'] = 'You dont have a '..Config.Wash.Dishes.Cup.Return.label, -- Notification
        ['noglass'] = 'You dont have a '..Config.Wash.Dishes.Glass.Return.label, -- Notification
        ['nopintglass'] = 'You dont have a '..Config.Wash.Dishes.PintGlass.Return.label, -- Notification
        ['nosmallglass'] = 'You dont have a '..Config.Wash.Dishes.SmallGlass.Return.label, -- Notification
        ['nowineglass'] = 'You dont have a '..Config.Wash.Dishes.WineGlass.Return.label, -- Notification
        ['nococktailglass'] = 'You dont have a '..Config.Wash.Dishes.CocktailGlass.Return.label, -- Notification
        ['washhands'] = 'Washing Hands..', -- Progressbar
        ['washface'] = 'Washing Face..', -- Progressbar
        ['washdishes'] = 'Washing Dishes..', -- Progressbar
        ['takingplate'] = 'Taking A Plate..', -- Progressbar
        ['storingplate'] = 'Storing A Plate..', -- Progressbar
        ['takingjar'] = 'Taking A Jar..', -- Progressbar
        ['storingjar'] = 'Storing A Jar..', -- Progressbar 
        ['takingcup'] = 'Taking A Cup..', -- Progressbar
        ['storingcup'] = 'Storing A Cup..', -- Progressbar 
        ['takingglass'] = 'Taking A Glass..', -- Progressbar
        ['storingglass'] = 'Storing A Glass..', -- Progressbar
        ['takingpintglass'] = 'Taking A Pint Glass..', -- Progressbar
        ['storingpintglass'] = 'Storing A Pint Glass..', -- Progressbar
        ['takingsmallglass'] = 'Taking A Small Glass..', -- Progressbar
        ['storingsmallglass'] = 'Storing A Small Glass..', -- Progressbar
        ['takingwineglass'] = 'Taking A Wine Glass..', -- Progressbar
        ['storingwineglass'] = 'Storing A Wine Glass..', -- Progressbar
        ['takingcocktailglass'] = 'Taking A Cocktail Glass..', -- Progressbar
        ['storingcocktailglass'] = 'Storing A Cocktail Glass..' -- Progressbar 
    },
    Bar = {
        ['pintheader'] = 'Pint', -- Menu header
        ['pintheadertext'] = 'Pull pints here!', -- Menu text
        ['pintheadericon'] = 'fa-solid fa-beer-mug-empty', -- Menu icon
        ['liquorheader'] = 'Liquor', -- Menu header
        ['liquorheadertext'] = 'Pour liquor here!', -- Menu text
        ['liquorheadericon'] = 'fa-solid fa-whiskey-glass', -- Menu icon
        ['wineheader'] = 'Wine', -- Menu header
        ['wineheadertext'] = 'Pour wine here!', -- Menu text
        ['wineheadericon'] = 'fa-solid fa-wine-glass', -- Menu icon
        ['amheader'] = 'AM Beer', -- Menu header
        ['amheadertext'] = 'Mornings golden shower.', -- Menu header text
        ['amheadericon'] = 'fa-solid fa-beer-mug-empty', -- Menu icon
        ['pisheader'] = 'Piswasser', -- Menu header
        ['pisheadertext'] = 'Youre in for a good time.', -- Menu header text
        ['pisheadericon'] = 'fa-solid fa-beer-mug-empty', -- Menu icon
        ['loggerheader'] = 'Logger', -- Menu header
        ['loggerheadertext'] = 'Best served with your sister.', -- Menu header text
        ['loggerheadericon'] = 'fa-solid fa-beer-mug-empty', -- Menu icon
        ['duscheheader'] = 'Dusche Gold', -- Menu header
        ['duscheheadertext'] = 'Let it pour.', -- Menu header text
        ['duscheheadericon'] = 'fa-solid fa-beer-mug-empty', -- Menu icon
        ['rumheader'] = 'Rum', -- Menu header
        ['rumheadertext'] = 'Jamaicas finest rum.', -- Menu header text
        ['rumheadericon'] = 'fa-solid fa-whiskey-glass', -- Menu icon
        ['whiskeyheader'] = 'Whiskey', -- Menu header
        ['whiskeyheadertext'] = 'Sour blend bourbon whiskey.', -- Menu header text
        ['whiskeyheadericon'] = 'fa-solid fa-whiskey-glass', -- Menu icon
        ['vodkaheader'] = 'Vodka', -- Menu header
        ['vodkaheadertext'] = 'Warms you to the core.', -- Menu header text
        ['vodkaheadericon'] = 'fa-solid fa-whiskey-glass', -- Menu icon
        ['chardonnayheader'] = 'Chardonnay', -- Menu header
        ['chardonnayheadertext'] = 'Chardonnay for after a really long, hard day.', -- Menu header text
        ['chardonnayheadericon'] = 'fa-solid fa-wine-glass', -- Menu icon
        ['baroloheader'] = 'Barolo', -- Menu header
        ['baroloheadertext'] = 'The King of Wines and the Wine of Kings.', -- Menu header text
        ['baroloheadericon'] = 'fa-solid fa-wine-glass', -- Menu icon
        ['pinotgrigioheader'] = 'Pinot Grigio', -- Menu header
        ['pinotgrigioheadertext'] = 'One should always be drunk. Thats all that matters.', -- Menu header text
        ['pinotgrigioheadericon'] = 'fa-solid fa-wine-glass', -- Menu icon
        ['pinotnoirheader'] = 'Pinot Noir', -- Menu header
        ['pinotnoirheadertext'] = 'If you drink no noir, you will pinot noir.', -- Menu header text
        ['pinotnoirheadericon'] = 'fa-solid fa-wine-glass', -- Menu icon
        ['nopintglass'] = 'You dont have a '..Config.Drinks.Pint.Required.label..'..', -- Notification
        ['nosmallglass'] = 'You dont have a '..Config.Drinks.Liquor.Required.label..'..', -- Notification
        ['nowineglass'] = 'You dont have a '..Config.Drinks.Wine.Required.label..'..', -- Notification
        ['nochardonnay'] = 'You dont have any '..Config.Drinks.Wine.Chardonnay.Required.label..'!', -- Notification
        ['nobarolo'] = 'You dont have any '..Config.Drinks.Wine.Barolo.Required.label..'!', -- Notification
        ['nopinotgrigio'] = 'You dont have any '..Config.Drinks.Wine.PinotGrigio.Required.label..'!', -- Notification
        ['nopinotnoir'] = 'You dont have any '..Config.Drinks.Wine.PinotNoir.Required.label..'!', -- Notification
        ['madeambeer'] = 'You pulled a '..Config.Drinks.Pint.AMBeer.Return.label..'!', -- Notification
        ['madepiswasser'] = 'You pulled a '..Config.Drinks.Pint.Piswasser.Return.label..'!', -- Notification
        ['madelogger'] = 'You pulled a '..Config.Drinks.Pint.Logger.Return.label..'!', -- Notification
        ['madedusche'] = 'You pulled a '..Config.Drinks.Pint.Dusche.Return.label..'!', -- Notification
        ['maderum'] = 'You pulled a '..Config.Drinks.Liquor.Rum.Return.label..'!', -- Notification
        ['madewhiskey'] = 'You pulled a '..Config.Drinks.Liquor.Whiskey.Return.label..'!', -- Notification
        ['madevodka'] = 'You pulled a '..Config.Drinks.Liquor.Vodka.Return.label..'!', -- Notification
        ['madechardonnay'] = 'You poured a '..Config.Drinks.Wine.Chardonnay.Return.label..'!', -- Notification
        ['madebarola'] = 'You poured a '..Config.Drinks.Wine.Barolo.Return.label..'!', -- Notification
        ['madepinotgrigio'] = 'You poured a '..Config.Drinks.Wine.PinotGrigio.Return.label..'!', -- Notification
        ['madepinotnoir'] = 'You poured a '..Config.Drinks.Wine.PinotNoir.Return.label..'!', -- Notification
        ['pullpint'] = 'Pulling Pint..', -- Progress bar
        ['pullliquor'] = 'Pulling Liquor..', -- Progress bar
        ['pourwine'] = 'Pouring Wine..', -- Progressbar
    },
    HotDrinks = {
        ['nocup'] = 'You dont have a '..Config.Drinks.Hot.Required.label, -- Notification
        ['madecoffee'] = 'You made a '..Config.Drinks.Hot.Coffee.Return.label..'!', -- Notification
        ['madetea'] = 'You made a '..Config.Drinks.Hot.Tea.Return.label..'!', -- Notification
        ['makehotdrink'] = 'Making A Hot Drink..', -- Progressbar
    },
    Microwave = {
        ['microwavemenuheader'] = 'Microwave', -- Menu header
        ['microwavemenuheadertext'] = 'Required:</p>1x Microwave meal or snack', -- Menu header text
        ['microwavemenuheadericon'] = 'fa-solid fa-biohazard', -- Menu header text
        ['pieicon'] = 'fa-solid fa-stroopwafel', -- Menu header text
        ['burgericon'] = 'fa-solid fa-burger', -- Menu header text
        ['cheesepieheader'] = 'Cheese & Onion Pie', -- Menu header
        ['cheesepieheadertext'] = 'Keep calm & have a pie!', -- Menu header
        ['meatpieheader'] = 'Meat Pie', -- Menu header
        ['meatpieheadertext'] = 'Keep calm & have a pie!', -- Menu header
        ['steakpieheader'] = 'Steak & Kidney Pie', -- Menu header
        ['steakpieheadertext'] = 'Keep calm & have a pie!', -- Menu header
        ['chickenpieheader'] = 'Chicken & Mushroom Pie', -- Menu header
        ['chickenpieheadertext'] = 'Keep calm & have a pie!', -- Menu header
        ['mwburgerheader'] = 'Burger', -- Menu header
        ['mwburgerheadertext'] = 'Not as fresh but still tasty!', -- Menu header
        ['mwcburgerheader'] = 'Cheeseurger', -- Menu header
        ['mwcburgerheadertext'] = 'Not as fresh but still tasty!', -- Menu header
        ['mwbcburgerheader'] = 'Bacon Cheeseburger', -- Menu header
        ['mwbcburgerheadertext'] = 'Not as fresh but still tasty!', -- Menu header
        ['mademicrowave'] = 'You successfully microwaved some food!', -- Notification
        ['nofood'] = 'What are you planning on cooking? The air? Dont be stupid..', -- Notification
        ['noplate'] = 'You need a Clean Plate to microwave food..', -- Notification
        ['usemicrowave'] = 'Putting Food In Microwave..', -- Progressbar
        ['microwavefood'] = 'Waiting for Microwave..', -- Progressbar
    },
    Cocktails = {
        ['cocktailsmenuheader'] = 'Cocktail Station', -- Menu header
        ['cocktailsmenuheadertext'] = 'Everyone loves a good cocktail!', -- Menu header text
        ['cocktailsmenuheadericon'] = 'fa-solid fa-blender', -- Menu header text
        ['cocktailswhiskeyheader'] = 'Whiskey Cocktails', -- Menu header
        ['cocktailswhiskeyheadertext'] = 'View available recipes!', -- Menu header text
        ['cocktailsrumheader'] = 'Rum Cocktails', -- Menu header
        ['cocktailsrumheadertext'] = 'View available recipes!', -- Menu header text
        ['cocktailsvodkaheader'] = 'Vodka Cocktails', -- Menu header
        ['cocktailsvodkaheadertext'] = 'View available recipes!', -- Menu header text
        ['drinksheadericon'] = 'fa-solid fa-martini-glass', -- Menu header text
        ['cocktailsicon'] = 'fa-solid fa-martini-glass-citrus', -- Menu icon
        ['whiskeysourheader'] = 'Whiskey Sour', -- Menu header
        ['whiskeysourheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.WhiskeySour.Required['1'].amount..'x '..Config.Drinks.Cocktails.WhiskeySour.Required['1'].label..'</p>'..Config.Drinks.Cocktails.WhiskeySour.Required['2'].amount..'x '..Config.Drinks.Cocktails.WhiskeySour.Required['2'].label..'</p>'..Config.Drinks.Cocktails.WhiskeySour.Required['3'].amount..'x '..Config.Drinks.Cocktails.WhiskeySour.Required['3'].label, -- Menu header text
        ['whiskeysmashheader'] = 'Whiskey Smash', -- Menu header
        ['whiskeysmashheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.WhiskeySmash.Required['1'].amount..'x '..Config.Drinks.Cocktails.WhiskeySmash.Required['1'].label..'</p>'..Config.Drinks.Cocktails.WhiskeySmash.Required['2'].amount..'x '..Config.Drinks.Cocktails.WhiskeySmash.Required['2'].label..'</p>'..Config.Drinks.Cocktails.WhiskeySmash.Required['3'].amount..'x '..Config.Drinks.Cocktails.WhiskeySmash.Required['3'].label, -- Menu header text
        ['bloodsandheader'] = 'Blood and Sand', -- Menu header
        ['bloodsandheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.BloodSand.Required['1'].amount..'x '..Config.Drinks.Cocktails.BloodSand.Required['1'].label..'</p>'..Config.Drinks.Cocktails.BloodSand.Required['2'].amount..'x '..Config.Drinks.Cocktails.BloodSand.Required['2'].label..'</p>'..Config.Drinks.Cocktails.BloodSand.Required['3'].amount..'x '..Config.Drinks.Cocktails.BloodSand.Required['3'].label, -- Menu header text
        ['pinacoladaheader'] = 'Pina Colada', -- Menu header
        ['pinacoladaheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.PinaColada.Required['1'].amount..'x '..Config.Drinks.Cocktails.PinaColada.Required['1'].label..'</p>'..Config.Drinks.Cocktails.PinaColada.Required['2'].amount..'x '..Config.Drinks.Cocktails.PinaColada.Required['2'].label..'</p>'..Config.Drinks.Cocktails.PinaColada.Required['3'].amount..'x '..Config.Drinks.Cocktails.PinaColada.Required['3'].label, -- Menu header text
        ['zombieheader'] = 'Zombie', -- Menu header
        ['zombieheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.Zombie.Required['1'].amount..'x '..Config.Drinks.Cocktails.Zombie.Required['1'].label..'</p>'..Config.Drinks.Cocktails.Zombie.Required['2'].amount..'x '..Config.Drinks.Cocktails.Zombie.Required['2'].label..'</p>'..Config.Drinks.Cocktails.Zombie.Required['3'].amount..'x '..Config.Drinks.Cocktails.Zombie.Required['3'].label, -- Menu header text
        ['maitaiheader'] = 'Mai Tai', -- Menu header
        ['maitaiheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.MaiTai.Required['1'].amount..'x '..Config.Drinks.Cocktails.MaiTai.Required['1'].label..'</p>'..Config.Drinks.Cocktails.MaiTai.Required['2'].amount..'x '..Config.Drinks.Cocktails.MaiTai.Required['2'].label..'</p>'..Config.Drinks.Cocktails.Appletini.Required['3'].amount..'x '..Config.Drinks.Cocktails.Appletini.Required['3'].label, -- Menu header text
        ['appletiniheader'] = 'Appletini', -- Menu header
        ['appletiniheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.Appletini.Required['1'].amount..'x '..Config.Drinks.Cocktails.Appletini.Required['1'].label..'</p>'..Config.Drinks.Cocktails.Appletini.Required['2'].amount..'x '..Config.Drinks.Cocktails.Appletini.Required['2'].label..'</p>'..Config.Drinks.Cocktails.MaiTai.Required['3'].amount..'x '..Config.Drinks.Cocktails.MaiTai.Required['3'].label, -- Menu header text
        ['cosmopolitanheader'] = 'Cosmopolitan', -- Menu header
        ['cosmopolitanheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.Cosmopolitan.Required['1'].amount..'x '..Config.Drinks.Cocktails.Cosmopolitan.Required['1'].label..'</p>'..Config.Drinks.Cocktails.Cosmopolitan.Required['2'].amount..'x '..Config.Drinks.Cocktails.Cosmopolitan.Required['2'].label..'</p>'..Config.Drinks.Cocktails.Cosmopolitan.Required['3'].amount..'x '..Config.Drinks.Cocktails.Cosmopolitan.Required['3'].label, -- Menu header text
        ['bloodymaryheader'] = 'Bloody Mary', -- Menu header
        ['bloodymaryheadertext'] = 'Ingredients:</p>'..Config.Drinks.Cocktails.BloodyMary.Required['1'].amount..'x '..Config.Drinks.Cocktails.BloodyMary.Required['1'].label..'</p>'..Config.Drinks.Cocktails.BloodyMary.Required['2'].amount..'x '..Config.Drinks.Cocktails.BloodyMary.Required['2'].label..'</p>'..Config.Drinks.Cocktails.BloodyMary.Required['3'].amount..'x '..Config.Drinks.Cocktails.BloodyMary.Required['3'].label, -- Menu header text
        ['enoughwhiskeysour1'] = 'You dont have enough '..Config.Drinks.Cocktails.WhiskeySour.Required['1'].label, -- Notification
        ['enoughwhiskeysour2'] = 'You dont have enough '..Config.Drinks.Cocktails.WhiskeySour.Required['2'].label, -- Notification
        ['enoughwhiskeysour3'] = 'You dont have enough '..Config.Drinks.Cocktails.WhiskeySour.Required['3'].label, -- Notification
        ['nowhiskeysour1'] = 'You dont have any '..Config.Drinks.Cocktails.WhiskeySour.Required['1'].label, -- Notification
        ['nowhiskeysour2'] = 'You dont have any '..Config.Drinks.Cocktails.WhiskeySour.Required['2'].label, -- Notification
        ['nowhiskeysour3'] = 'You dont have any '..Config.Drinks.Cocktails.WhiskeySour.Required['3'].label, -- Notification
        ['enoughwhiskeysmash1'] = 'You dont have enough '..Config.Drinks.Cocktails.WhiskeySmash.Required['1'].label, -- Notification
        ['enoughwhiskeysmash2'] = 'You dont have enough '..Config.Drinks.Cocktails.WhiskeySmash.Required['2'].label, -- Notification
        ['enoughwhiskeysmash3'] = 'You dont have enough '..Config.Drinks.Cocktails.WhiskeySmash.Required['3'].label, -- Notification
        ['nowhiskeysmash1'] = 'You dont have any '..Config.Drinks.Cocktails.WhiskeySmash.Required['1'].label, -- Notification
        ['nowhiskeysmash2'] = 'You dont have any '..Config.Drinks.Cocktails.WhiskeySmash.Required['2'].label, -- Notification
        ['nowhiskeysmash3'] = 'You dont have any '..Config.Drinks.Cocktails.WhiskeySmash.Required['3'].label, -- Notification
        ['enoughbloodsand1'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodSand.Required['1'].label, -- Notification
        ['enoughbloodsand2'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodSand.Required['2'].label, -- Notification
        ['enoughbloodsand3'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodSand.Required['3'].label, -- Notification
        ['nobloodsand1'] = 'You dont have any '..Config.Drinks.Cocktails.BloodSand.Required['1'].label, -- Notification
        ['nobloodsand2'] = 'You dont have any '..Config.Drinks.Cocktails.BloodSand.Required['2'].label, -- Notification
        ['nobloodsand3'] = 'You dont have any '..Config.Drinks.Cocktails.BloodSand.Required['3'].label, -- Notification
        ['enoughbloodsand1'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodSand.Required['1'].label, -- Notification
        ['enoughbloodsand2'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodSand.Required['2'].label, -- Notification
        ['enoughbloodsand3'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodSand.Required['3'].label, -- Notification
        ['nobloodsand1'] = 'You dont have any '..Config.Drinks.Cocktails.BloodSand.Required['1'].label, -- Notification
        ['nobloodsand2'] = 'You dont have any '..Config.Drinks.Cocktails.BloodSand.Required['2'].label, -- Notification
        ['nobloodsand3'] = 'You dont have any '..Config.Drinks.Cocktails.BloodSand.Required['3'].label, -- Notification
        ['enoughzombie1'] = 'You dont have enough '..Config.Drinks.Cocktails.Zombie.Required['1'].label, -- Notification
        ['enoughzombie2'] = 'You dont have enough '..Config.Drinks.Cocktails.Zombie.Required['2'].label, -- Notification
        ['enoughzombie3'] = 'You dont have enough '..Config.Drinks.Cocktails.Zombie.Required['3'].label, -- Notification
        ['nozombie1'] = 'You dont have any '..Config.Drinks.Cocktails.Zombie.Required['1'].label, -- Notification
        ['nozombie2'] = 'You dont have any '..Config.Drinks.Cocktails.Zombie.Required['2'].label, -- Notification
        ['nozombie3'] = 'You dont have any '..Config.Drinks.Cocktails.Zombie.Required['3'].label, -- Notification
        ['enoughmaitai1'] = 'You dont have enough '..Config.Drinks.Cocktails.MaiTai.Required['1'].label, -- Notification
        ['enoughmaitai2'] = 'You dont have enough '..Config.Drinks.Cocktails.MaiTai.Required['2'].label, -- Notification
        ['enoughmaitai3'] = 'You dont have enough '..Config.Drinks.Cocktails.MaiTai.Required['3'].label, -- Notification
        ['nomaitai1'] = 'You dont have any '..Config.Drinks.Cocktails.MaiTai.Required['1'].label, -- Notification
        ['nomaitai2'] = 'You dont have any '..Config.Drinks.Cocktails.MaiTai.Required['2'].label, -- Notification
        ['nomaitai3'] = 'You dont have any '..Config.Drinks.Cocktails.MaiTai.Required['3'].label, -- Notification
        ['enoughappletini1'] = 'You dont have enough '..Config.Drinks.Cocktails.Appletini.Required['1'].label, -- Notification
        ['enoughappletini2'] = 'You dont have enough '..Config.Drinks.Cocktails.Appletini.Required['2'].label, -- Notification
        ['enoughappletini3'] = 'You dont have enough '..Config.Drinks.Cocktails.Appletini.Required['3'].label, -- Notification
        ['noappletini1'] = 'You dont have any '..Config.Drinks.Cocktails.Appletini.Required['1'].label, -- Notification
        ['noappletini2'] = 'You dont have any '..Config.Drinks.Cocktails.Appletini.Required['2'].label, -- Notification
        ['noappletini3'] = 'You dont have any '..Config.Drinks.Cocktails.Appletini.Required['3'].label, -- Notification
        ['enoughcosmopolitan1'] = 'You dont have enough '..Config.Drinks.Cocktails.Cosmopolitan.Required['1'].label, -- Notification
        ['enoughcosmopolitan2'] = 'You dont have enough '..Config.Drinks.Cocktails.Cosmopolitan.Required['2'].label, -- Notification
        ['enoughcosmopolitan3'] = 'You dont have enough '..Config.Drinks.Cocktails.Cosmopolitan.Required['3'].label, -- Notification
        ['nocosmopolitan1'] = 'You dont have any '..Config.Drinks.Cocktails.Cosmopolitan.Required['1'].label, -- Notification
        ['nocosmopolitan2'] = 'You dont have any '..Config.Drinks.Cocktails.Cosmopolitan.Required['2'].label, -- Notification
        ['nocosmopolitan3'] = 'You dont have any '..Config.Drinks.Cocktails.Cosmopolitan.Required['3'].label, -- Notification
        ['enoughbloodymary1'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodyMary.Required['1'].label, -- Notification
        ['enoughbloodymary2'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodyMary.Required['2'].label, -- Notification
        ['enoughbloodymary3'] = 'You dont have enough '..Config.Drinks.Cocktails.BloodyMary.Required['3'].label, -- Notification
        ['nobloodymary1'] = 'You dont have any '..Config.Drinks.Cocktails.BloodyMary.Required['1'].label, -- Notification
        ['nobloodymary2'] = 'You dont have any '..Config.Drinks.Cocktails.BloodyMary.Required['2'].label, -- Notification
        ['nobloodymary3'] = 'You dont have any '..Config.Drinks.Cocktails.BloodyMary.Required['3'].label, -- Notification
        ['nococktailglass'] = 'You need a cocktail glass stupid..', -- Notification
        ['madecocktail'] = 'You successfully mixed a cocktail!', -- Notification
        ['mixingcocktail'] = 'Mixing Cocktail..', -- Progressbar
    },
    Snake = {
        ['nomouse'] = 'You dont have a '..Config.Snake.Item.label..'..', -- Notification
        ['hasmouse'] = 'You already have a '..Config.Snake.Item.label..'..', -- Notification
        ['fedsnake'] = 'You fed the snake!', -- Notification
    },
    Garage = {
        ['returnedvan'] = 'Thank you for returning the van!', -- Notification
        ['rentedvan'] = 'You took out a van! Return it when your done!', -- Notification
        ['nomoney'] = 'You cant afford the deposit dumbass..', -- Notification
        ['rentheader'] = 'Billiards Bar Garage', -- Menu header
        ['rentheadericon'] = 'fa-solid fa-warehouse', -- Menu header
        ['rentmenuheader'] = 'Company Van', -- Menu header
        ['rentmenutext'] = 'A deposit of $'..Config.Garage.Deposit..' is required.', -- Menu text
        ['rentmenuicon'] = 'fa-solid fa-car', -- Menu icon
        ['returnmenuheader'] = 'Return Van', -- Menu header
        ['returnmenutext'] = 'Return Vehicle to receive $'..math.floor(Config.Garage.Deposit/2), -- Menu text
        ['returnmenuicon'] = 'fa-solid fa-car', -- Menu icon
    },
    Shared = {
        ['returnmenu'] = 'Return', -- Menu header
        ['returnmenuicon'] = 'fa-solid fa-backward', -- Menu header icon
        ['exitmenu'] = 'Exit', -- Menu header
        ['exitmenuicon'] = 'fa-solid fa-circle-xmark', -- Menu header icon
        ['cancelled'] = 'Action cancelled..', -- Notification
        ['noinvent'] = 'Looks like your pockets are full..', -- Notification
        ['outrange'] = 'Looks like you are too far away..', -- Notification
        ['forceentry'] = 'Forcing Entry..' -- Progressbar
    }
}
    