Config = {}

Config.UseTarget = GetConvar('UseTarget', 'false') == 'true'

Config.PoliceOpen = true -- Can Police open all stashes

Config.Stashes = {
     ["triads"] = {
         canAnyoneOpen = false,
         stashName = "triads",
         coords = vector3(-652.75, -1230.86, 11.55), 
         requirecid = false,
         jobrequired = false,
         gangrequired = true,
         gang = "triads",
         job = "triads",
         cid = {""},  
         stashSize = 12500000,
         stashSlots = 350, 
     },
	 ["jokersmc"] = {
         canAnyoneOpen = false,
         stashName = "jokersmc",
         coords = vector3(-1186.59, -1164.03, 0.71), 
         requirecid = false,
         jobrequired = false,
         gangrequired = true,
         gang = "jokersmc",
         job = "jokersmc",
         cid = {""},  
         stashSize = 12500000,
         stashSlots = 350, 
     },
	["pdlocker"] = {
         canAnyoneOpen = false,
         stashName = "pdlocker",
         coords = vector3(462.18, -995.89, 30.69), 
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "police",
         cid = {""},  
         stashSize = 12500000,
         stashSlots = 250, 
     },
	 ["bslocker"] = {
         canAnyoneOpen = false,
         stashName = "bslocker",
         coords = vector3(-1181.92, -899.45, 13.97), 
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "burgershot",
         cid = {""},  
         stashSize = 12500000,
         stashSlots = 250, 
     },
	 ["bmlocker"] = {
         canAnyoneOpen = false,
         stashName = "bmlocker",
         coords = vector3(122.79, -1043.94, 29.28), 
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "beanmachine",
         cid = {""},  
         stashSize = 12500000,
         stashSlots = 250, 
     },
	 ["rtlocker"] = {
         canAnyoneOpen = false,
         stashName = "rtlocker",
         coords = vector3(-1582.68, -990.89, 13.08), 
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "billiards",
         cid = {""},  
         stashSize = 1250000,
         stashSlots = 250, 
     },
	 ["mechaniclocker"] = {
         canAnyoneOpen = false,
         stashName = "mechaniclocker",
         coords = vector3(153.94, -3011.39, 7.04), 
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "mechanic",
         cid = {""},  
         stashSize = 125000000,
         stashSlots = 250, 
     },
	 ["vulocker"] = {
         canAnyoneOpen = false,
         stashName = "vulocker",
         coords = vector3(106.47, -1299.53, 28.77), 
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "vanilla",
         cid = {""},  
         stashSize = 125000000,
         stashSlots = 250, 
	},
	["coretttosstash"] = {
         canAnyoneOpen = false,
         stashName = "beamersstash",
         coords = vector3(-1188.55, -1386.64, 4.67), 
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "corettos",
         cid = {""},  
         stashSize = 125000000,
         stashSlots = 250, 
	},
	["whitewidowstash"] = {
         canAnyoneOpen = false,
         stashName = "whitewidowstash",
         coords = vector3(193.26, -258.82, 54.1), 
         requirecid = false,
         jobrequired = true,
         gangrequired = false,
         gang = "",
         job = "whitewidow",
         cid = {""},  
         stashSize = 125000000,
         stashSlots = 250, 
	},
	["7055stash"] = {
         canAnyoneOpen = false,
         stashName = "70558stash",
         coords = vector3(-1122.44, 361.65, 71.31), 
         requirecid = false,
         jobrequired = false,
         gangrequired = true,
         gang = "triads",
         job = "",
         cid = {""},  
         stashSize = 125000000,
         stashSlots = 250, 
	},
	["7155stash"] = {
         canAnyoneOpen = false,
         stashName = "7156stash",
         coords = vector3(-903.28, -1.88, 39.86), 
         requirecid = true,
         jobrequired = false,
         gangrequired = false,
         gang = "",
         job = "",
         cid = {"ZZI08931"},  
         stashSize = 125000000,
         stashSlots = 250, 
	},
	["6013stash"] = {
         canAnyoneOpen = false,
         stashName = "6103stash",
         coords = vector3(-2005.25, 299.75, 91.77), 
         requirecid = true,
         jobrequired = false,
         gangrequired = false,
         gang = "",
         job = "",
         cid = {"UMV17620"},  
         stashSize = 125000000,
         stashSlots = 250, 
	},
	["6070stash"] = {
         canAnyoneOpen = false,
         stashName = "6070stash",
         coords = vector3(-101.58, 998.81, 240.84), 
         requirecid = true,
         jobrequired = false,
         gangrequired = false,
         gang = "",
         job = "",
         cid = {"IRA48869"},  
         stashSize = 125000000,
         stashSlots = 250, 
	},
}
