
BackItems = {
    ["markedbills"] = { -- Item Name
        model="prop_money_bag_01", -- Model you want to display
        back_bone = 24818, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = -0.4,
        y = -0.17,
        z = -0.12,
        -- Rotaion of the object.
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
	["skateboard"] = {
        model="v_res_skateboard", 
        back_bone = 24818,
        x = 0.05,
        y = -0.25,
        z = -0.02,
        x_rotation = 270.0,
        y_rotation = 180.0,
        z_rotation = 0.0,
    },
    ["meth"] = {
        model="hei_prop_pill_bag_01", 
        back_bone = 24818,
        x = -0.1,
        y = -0.17,
        z = 0.12,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ["weapon_bat"] = {
        model="w_me_bat", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_bottle"] = {
        model="w_me_bottle", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_crowbar"] = {
        model="w_me_crowbar", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_dagger"] = {
        model="w_me_dagger", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_golfclub"] = {
        model="w_me_gclub", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_nightstick"] = {
        model="w_me_nightstick", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_katana"] = {
        model="w_me_katana", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_shiv"] = {
        model="w_me_shiv", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="w_me_sledgehammer", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="prop_w_me_hatchet", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="prop_w_me_knife_01", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="prop_tool_wrench", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="w_me_sledgehammer", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="w_me_sledgehammer", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="w_me_sledgehammer", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="w_me_sledgehammer", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="w_me_sledgehammer", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },
    ["weapon_sledgehammer"] = {
        model="w_me_sledgehammer", 
        back_bone = 24818,
        x = -0.13,
        y = -0.15,
        z = 0.09,
        x_rotation = 0.0,
        y_rotation = -90.0,
        z_rotation = 180.0,
    },

    ["weapon_smg"] = {
        model="w_sb_smg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_assaultrifle"] = {
        model="w_ar_assaultrifle",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_carbinerifle"] = {
        model="w_ar_carbinerifle", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_advancedrifle"] = {
        model="w_ar_advancedrifle",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_bullpuprifle"] = {
        model="w_ar_bullpuprifle",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_musket"] = {
        model="w_ar_musket",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_specialcarbine"] = {
        model="w_ar_specialcarbine",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_grenade"] = {
        model="w_ex_grenadefrag",
        back_bone = 24818,
        x = -0.15,
        y = -0.17,
        z = -0.09,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_bzgas"] = {
        model="w_ex_grenadesmoke",
        back_bone = 24818,
        x = -0.15,
        y = -0.17,
        z = -0.09,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_molotov"] = {
        model="w_ex_molotov",
        back_bone = 24818,
        x = -0.15,
        y = -0.17,
        z = -0.09,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_stickybomb"] = {
        model="w_ex_pe",
        back_bone = 24818,
        x = -0.15,
        y = -0.17,
        z = -0.09,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_snowball"] = {
        model="w_ex_snowball",
        back_bone = 24818,
        x = -0.15,
        y = -0.17,
        z = -0.09,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_grenadelauncher"] = {
        model="w_lr_grenadelauncher",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_combatmg"] = {
        model="w_mg_combatmg",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_mg"] = {
        model="w_mg_mg",
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_bullpupshotgun"] = {
        model="w_sg_bullpupshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_heavyshotgun"] = {
        model="w_sg_heavyshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_pumpshotgun"] = {
        model="w_sg_pumpshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_sawnoffshotgun"] = {
        model="w_sg_sawnoff", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_marksmanrifle"] = {
        model="w_sr_marksmanrifle", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_minigun"] = {
        model="w_mg_minigun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_appistol"] = {
        model="w_pi_appistol", 
        back_bone = 24818,
        x = -0.38,
        y = 0.06,
        z = -0.21,
        x_rotation = -90.0,
        y_rotation = -185.0,
        z_rotation = 0.0,
    },
    ["weapon_combatpistol"] = {
        model="w_pi_combatpistol", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_flaregun"] = {
        model="w_pi_flaregun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_pistol"] = {
        model="w_pi_pistol", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_snspistol"] = {
        model="w_pi_sns_pistol", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_stungun_mp"] = {
        model="w_pi_stungun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_gusenberg"] = {
        model="w_sb_gusenberg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_microsmg"] = {
        model="w_sb_microsmg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_autoshotgun"] = {
        model="w_sg_assaultshotgun", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_ar15"] = {
        model="w_ar_ar15", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_hk416"] = {
        model="w_ar_hk416", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_huntingrifle"] = {
        model="w_sr_huntingrifle", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_m4"] = {
        model="w_ar_m4", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_m70"] = {
        model="w_ar_m70", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["w_sr_m110"] = {
        model="w_sr_m110", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_mk14"] = {
        model="w_sr_mk14", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_mossberg"] = {
        model="w_sg_mossberg", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_remington"] = {
        model="w_sg_remington", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_scarh"] = {
        model="w_ar_scarh", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_de"] = {
        model="w_pi_de_luxe", 
        back_bone = 24818,
        x = -0.38,
        y = 0.06,
        z = -0.21,
        x_rotation = -90.0,
        y_rotation = -185.0,
        z_rotation = 0.0,
    },
    ["weapon_fnx45"] = {
        model="w_pi_fnx45", 
        back_bone = 24818,
        x = -0.38,
        y = 0.06,
        z = -0.21,
        x_rotation = -90.0,
        y_rotation = -185.0,
        z_rotation = 0.0,
    },
    ["weapon_glock17"] = {
        model="w_pi_glock17_luxe", 
        back_bone = 24818,
        x = -0.38,
        y = 0.06,
        z = -0.21,
        x_rotation = -90.0,
        y_rotation = -185.0,
        z_rotation = 0.0,
    },
    ["weapon_m9"] = {
        model="w_pi_m9", 
        back_bone = 24818,
        x = -0.38,
        y = 0.06,
        z = -0.21,
        x_rotation = -90.0,
        y_rotation = -185.0,
        z_rotation = 0.0,
    },
    ["weapon_m1911"] = {
        model="w_pi_m1911", 
        back_bone = 24818,
        x = -0.38,
        y = 0.06,
        z = -0.21,
        x_rotation = -90.0,
        y_rotation = -185.0,
        z_rotation = 0.0,
    },
    ["weapon_mac10"] = {
        model="w_sb_mac10", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_mp9"] = {
        model="w_sb_mp9", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_uzi"] = {
        model="w_sb_uzi", 
        back_bone = 24818,
        x = 0.0,
        y = -0.17,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_rpg"] = {
        model="w_lr_rpg", 
        back_bone = 24818,
        x = 0.2,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ["coke_brick"] = {
        model="bkr_prop_coke_cutblock_01", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 90.0,
    },
    ["weed_zkittlez_cbd_crop"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ["weed_gelato_cbd_crop"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ["weed_purple-haze_cbd_crop"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ["weed_amnesia_cbd_crop"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ["weed_ak47_cbd_crop"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ["weed_white-widow_cbd_crop"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ["weed_og-kush_cbd_crop"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    ["weed_skunk_cbd_crop"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
}
